// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: anchor_type.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AnchorInfo 主播基础信息
type AnchorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnchorOpenId  string                 `protobuf:"bytes,1,opt,name=anchor_open_id,json=anchorOpenId,proto3" json:"anchor_open_id,omitempty"` // 主播OpenID
	AvatarUrl     string                 `protobuf:"bytes,2,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`            // 主播头像
	NickName      string                 `protobuf:"bytes,3,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`               // 主播昵称
	SceneId       uint32                 `protobuf:"varint,4,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`                 // 场景ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnchorInfo) Reset() {
	*x = AnchorInfo{}
	mi := &file_anchor_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnchorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnchorInfo) ProtoMessage() {}

func (x *AnchorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_anchor_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnchorInfo.ProtoReflect.Descriptor instead.
func (*AnchorInfo) Descriptor() ([]byte, []int) {
	return file_anchor_type_proto_rawDescGZIP(), []int{0}
}

func (x *AnchorInfo) GetAnchorOpenId() string {
	if x != nil {
		return x.AnchorOpenId
	}
	return ""
}

func (x *AnchorInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *AnchorInfo) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *AnchorInfo) GetSceneId() uint32 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

var File_anchor_type_proto protoreflect.FileDescriptor

const file_anchor_type_proto_rawDesc = "" +
	"\n" +
	"\x11anchor_type.proto\x12\x04game\"\x89\x01\n" +
	"\n" +
	"AnchorInfo\x12$\n" +
	"\x0eanchor_open_id\x18\x01 \x01(\tR\fanchorOpenId\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x02 \x01(\tR\tavatarUrl\x12\x1b\n" +
	"\tnick_name\x18\x03 \x01(\tR\bnickName\x12\x19\n" +
	"\bscene_id\x18\x04 \x01(\rR\asceneIdB1Z/github.com/lk2023060901/xiaojia-proto-game;gameb\x06proto3"

var (
	file_anchor_type_proto_rawDescOnce sync.Once
	file_anchor_type_proto_rawDescData []byte
)

func file_anchor_type_proto_rawDescGZIP() []byte {
	file_anchor_type_proto_rawDescOnce.Do(func() {
		file_anchor_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_anchor_type_proto_rawDesc), len(file_anchor_type_proto_rawDesc)))
	})
	return file_anchor_type_proto_rawDescData
}

var file_anchor_type_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_anchor_type_proto_goTypes = []any{
	(*AnchorInfo)(nil), // 0: game.AnchorInfo
}
var file_anchor_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_anchor_type_proto_init() }
func file_anchor_type_proto_init() {
	if File_anchor_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_anchor_type_proto_rawDesc), len(file_anchor_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_anchor_type_proto_goTypes,
		DependencyIndexes: file_anchor_type_proto_depIdxs,
		MessageInfos:      file_anchor_type_proto_msgTypes,
	}.Build()
	File_anchor_type_proto = out.File
	file_anchor_type_proto_goTypes = nil
	file_anchor_type_proto_depIdxs = nil
}
