// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: anchor.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SyncAnchorInfo [S2C] 同步当前主播的详细信息
type SyncAnchorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Anchor        *AnchorInfo            `protobuf:"bytes,1,opt,name=anchor,proto3" json:"anchor,omitempty"` // 主播详细数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncAnchorInfo) Reset() {
	*x = SyncAnchorInfo{}
	mi := &file_anchor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAnchorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAnchorInfo) ProtoMessage() {}

func (x *SyncAnchorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_anchor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAnchorInfo.ProtoReflect.Descriptor instead.
func (*SyncAnchorInfo) Descriptor() ([]byte, []int) {
	return file_anchor_proto_rawDescGZIP(), []int{0}
}

func (x *SyncAnchorInfo) GetAnchor() *AnchorInfo {
	if x != nil {
		return x.Anchor
	}
	return nil
}

// SwitchAnchorSceneReq [C2S] 主播请求切换场景
type SwitchAnchorSceneReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SceneId       uint32                 `protobuf:"varint,1,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"` // 目标场景ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchAnchorSceneReq) Reset() {
	*x = SwitchAnchorSceneReq{}
	mi := &file_anchor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchAnchorSceneReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchAnchorSceneReq) ProtoMessage() {}

func (x *SwitchAnchorSceneReq) ProtoReflect() protoreflect.Message {
	mi := &file_anchor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchAnchorSceneReq.ProtoReflect.Descriptor instead.
func (*SwitchAnchorSceneReq) Descriptor() ([]byte, []int) {
	return file_anchor_proto_rawDescGZIP(), []int{1}
}

func (x *SwitchAnchorSceneReq) GetSceneId() uint32 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

// SwitchAnchorSceneRes [S2C] 主播切换场景响应
type SwitchAnchorSceneRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrCode                `protobuf:"varint,1,opt,name=code,proto3,enum=game.ErrCode" json:"code,omitempty"`    // 错误码
	SceneId       uint32                 `protobuf:"varint,2,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"` // 切换成功后的场景ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchAnchorSceneRes) Reset() {
	*x = SwitchAnchorSceneRes{}
	mi := &file_anchor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchAnchorSceneRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchAnchorSceneRes) ProtoMessage() {}

func (x *SwitchAnchorSceneRes) ProtoReflect() protoreflect.Message {
	mi := &file_anchor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchAnchorSceneRes.ProtoReflect.Descriptor instead.
func (*SwitchAnchorSceneRes) Descriptor() ([]byte, []int) {
	return file_anchor_proto_rawDescGZIP(), []int{2}
}

func (x *SwitchAnchorSceneRes) GetCode() ErrCode {
	if x != nil {
		return x.Code
	}
	return ErrCode_ERR_SUCCESS
}

func (x *SwitchAnchorSceneRes) GetSceneId() uint32 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

var File_anchor_proto protoreflect.FileDescriptor

const file_anchor_proto_rawDesc = "" +
	"\n" +
	"\fanchor.proto\x12\x04game\x1a\x11anchor_type.proto\x1a\x0eerr_code.proto\":\n" +
	"\x0eSyncAnchorInfo\x12(\n" +
	"\x06anchor\x18\x01 \x01(\v2\x10.game.AnchorInfoR\x06anchor\"1\n" +
	"\x14SwitchAnchorSceneReq\x12\x19\n" +
	"\bscene_id\x18\x01 \x01(\rR\asceneId\"T\n" +
	"\x14SwitchAnchorSceneRes\x12!\n" +
	"\x04code\x18\x01 \x01(\x0e2\r.game.ErrCodeR\x04code\x12\x19\n" +
	"\bscene_id\x18\x02 \x01(\rR\asceneIdB1Z/github.com/lk2023060901/xiaojia-proto-game;gameb\x06proto3"

var (
	file_anchor_proto_rawDescOnce sync.Once
	file_anchor_proto_rawDescData []byte
)

func file_anchor_proto_rawDescGZIP() []byte {
	file_anchor_proto_rawDescOnce.Do(func() {
		file_anchor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_anchor_proto_rawDesc), len(file_anchor_proto_rawDesc)))
	})
	return file_anchor_proto_rawDescData
}

var file_anchor_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_anchor_proto_goTypes = []any{
	(*SyncAnchorInfo)(nil),       // 0: game.SyncAnchorInfo
	(*SwitchAnchorSceneReq)(nil), // 1: game.SwitchAnchorSceneReq
	(*SwitchAnchorSceneRes)(nil), // 2: game.SwitchAnchorSceneRes
	(*AnchorInfo)(nil),           // 3: game.AnchorInfo
	(ErrCode)(0),                 // 4: game.ErrCode
}
var file_anchor_proto_depIdxs = []int32{
	3, // 0: game.SyncAnchorInfo.anchor:type_name -> game.AnchorInfo
	4, // 1: game.SwitchAnchorSceneRes.code:type_name -> game.ErrCode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_anchor_proto_init() }
func file_anchor_proto_init() {
	if File_anchor_proto != nil {
		return
	}
	file_anchor_type_proto_init()
	file_err_code_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_anchor_proto_rawDesc), len(file_anchor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_anchor_proto_goTypes,
		DependencyIndexes: file_anchor_proto_depIdxs,
		MessageInfos:      file_anchor_proto_msgTypes,
	}.Build()
	File_anchor_proto = out.File
	file_anchor_proto_goTypes = nil
	file_anchor_proto_depIdxs = nil
}
