// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: bed.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SyncBedValue [S2C] 同步床位数值(保护值/封印值)变动
type SyncBedValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        uint32                 `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`                                 // 槽位编号
	ValueType     BedValueType           `protobuf:"varint,2,opt,name=value_type,json=valueType,proto3,enum=game.BedValueType" json:"value_type,omitempty"` // 数值类型
	OpType        BedOpType              `protobuf:"varint,3,opt,name=op_type,json=opType,proto3,enum=game.BedOpType" json:"op_type,omitempty"`             // 操作类型
	Value         uint32                 `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`                                                 // 变动的数值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncBedValue) Reset() {
	*x = SyncBedValue{}
	mi := &file_bed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncBedValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncBedValue) ProtoMessage() {}

func (x *SyncBedValue) ProtoReflect() protoreflect.Message {
	mi := &file_bed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncBedValue.ProtoReflect.Descriptor instead.
func (*SyncBedValue) Descriptor() ([]byte, []int) {
	return file_bed_proto_rawDescGZIP(), []int{0}
}

func (x *SyncBedValue) GetSlotId() uint32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *SyncBedValue) GetValueType() BedValueType {
	if x != nil {
		return x.ValueType
	}
	return BedValueType_BED_VALUE_PROTECTION
}

func (x *SyncBedValue) GetOpType() BedOpType {
	if x != nil {
		return x.OpType
	}
	return BedOpType_BED_OP_ADD
}

func (x *SyncBedValue) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_bed_proto protoreflect.FileDescriptor

const file_bed_proto_rawDesc = "" +
	"\n" +
	"\tbed.proto\x12\x04game\x1a\x0ebed_type.proto\"\x9a\x01\n" +
	"\fSyncBedValue\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\rR\x06slotId\x121\n" +
	"\n" +
	"value_type\x18\x02 \x01(\x0e2\x12.game.BedValueTypeR\tvalueType\x12(\n" +
	"\aop_type\x18\x03 \x01(\x0e2\x0f.game.BedOpTypeR\x06opType\x12\x14\n" +
	"\x05value\x18\x04 \x01(\rR\x05valueB1Z/github.com/lk2023060901/xiaojia-proto-game;gameb\x06proto3"

var (
	file_bed_proto_rawDescOnce sync.Once
	file_bed_proto_rawDescData []byte
)

func file_bed_proto_rawDescGZIP() []byte {
	file_bed_proto_rawDescOnce.Do(func() {
		file_bed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bed_proto_rawDesc), len(file_bed_proto_rawDesc)))
	})
	return file_bed_proto_rawDescData
}

var file_bed_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bed_proto_goTypes = []any{
	(*SyncBedValue)(nil), // 0: game.SyncBedValue
	(BedValueType)(0),    // 1: game.BedValueType
	(BedOpType)(0),       // 2: game.BedOpType
}
var file_bed_proto_depIdxs = []int32{
	1, // 0: game.SyncBedValue.value_type:type_name -> game.BedValueType
	2, // 1: game.SyncBedValue.op_type:type_name -> game.BedOpType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_bed_proto_init() }
func file_bed_proto_init() {
	if File_bed_proto != nil {
		return
	}
	file_bed_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bed_proto_rawDesc), len(file_bed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bed_proto_goTypes,
		DependencyIndexes: file_bed_proto_depIdxs,
		MessageInfos:      file_bed_proto_msgTypes,
	}.Build()
	File_bed_proto = out.File
	file_bed_proto_goTypes = nil
	file_bed_proto_depIdxs = nil
}
