// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: bed_type.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BedOpType 变化操作类型
type BedOpType int32

const (
	BedOpType_BED_OP_ADD BedOpType = 0 // 增加
	BedOpType_BED_OP_SUB BedOpType = 1 // 减少
)

// Enum value maps for BedOpType.
var (
	BedOpType_name = map[int32]string{
		0: "BED_OP_ADD",
		1: "BED_OP_SUB",
	}
	BedOpType_value = map[string]int32{
		"BED_OP_ADD": 0,
		"BED_OP_SUB": 1,
	}
)

func (x BedOpType) Enum() *BedOpType {
	p := new(BedOpType)
	*p = x
	return p
}

func (x BedOpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BedOpType) Descriptor() protoreflect.EnumDescriptor {
	return file_bed_type_proto_enumTypes[0].Descriptor()
}

func (BedOpType) Type() protoreflect.EnumType {
	return &file_bed_type_proto_enumTypes[0]
}

func (x BedOpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BedOpType.Descriptor instead.
func (BedOpType) EnumDescriptor() ([]byte, []int) {
	return file_bed_type_proto_rawDescGZIP(), []int{0}
}

// BedValueType 数值类型
type BedValueType int32

const (
	BedValueType_BED_VALUE_PROTECTION BedValueType = 0 // 保护值
	BedValueType_BED_VALUE_SEAL       BedValueType = 1 // 封印值
	BedValueType_BED_VALUE_ENERGY     BedValueType = 2 // 装饰能量
)

// Enum value maps for BedValueType.
var (
	BedValueType_name = map[int32]string{
		0: "BED_VALUE_PROTECTION",
		1: "BED_VALUE_SEAL",
		2: "BED_VALUE_ENERGY",
	}
	BedValueType_value = map[string]int32{
		"BED_VALUE_PROTECTION": 0,
		"BED_VALUE_SEAL":       1,
		"BED_VALUE_ENERGY":     2,
	}
)

func (x BedValueType) Enum() *BedValueType {
	p := new(BedValueType)
	*p = x
	return p
}

func (x BedValueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BedValueType) Descriptor() protoreflect.EnumDescriptor {
	return file_bed_type_proto_enumTypes[1].Descriptor()
}

func (BedValueType) Type() protoreflect.EnumType {
	return &file_bed_type_proto_enumTypes[1]
}

func (x BedValueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BedValueType.Descriptor instead.
func (BedValueType) EnumDescriptor() ([]byte, []int) {
	return file_bed_type_proto_rawDescGZIP(), []int{1}
}

// BedPkInfo 床位PK实时过程数据
type BedPkInfo struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Challenger           *PlayerInfo            `protobuf:"bytes,1,opt,name=challenger,proto3" json:"challenger,omitempty"`                                                 // 挑战者信息
	OwnerScore           int64                  `protobuf:"varint,2,opt,name=owner_score,json=ownerScore,proto3" json:"owner_score,omitempty"`                              // 所有者积分 (本轮PK获得)
	ChallengerScore      int64                  `protobuf:"varint,3,opt,name=challenger_score,json=challengerScore,proto3" json:"challenger_score,omitempty"`               // 挑战者积分
	TotalCountdown       uint32                 `protobuf:"varint,4,opt,name=total_countdown,json=totalCountdown,proto3" json:"total_countdown,omitempty"`                  // PK剩余总时长 (秒)
	OwnerSupporters      []*PlayerInfo          `protobuf:"bytes,5,rep,name=owner_supporters,json=ownerSupporters,proto3" json:"owner_supporters,omitempty"`                // 所有者支持者列表(刷礼物的用户)
	ChallengerSupporters []*PlayerInfo          `protobuf:"bytes,6,rep,name=challenger_supporters,json=challengerSupporters,proto3" json:"challenger_supporters,omitempty"` // 挑战者支持者列表(刷礼物的用户)
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *BedPkInfo) Reset() {
	*x = BedPkInfo{}
	mi := &file_bed_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BedPkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BedPkInfo) ProtoMessage() {}

func (x *BedPkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bed_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BedPkInfo.ProtoReflect.Descriptor instead.
func (*BedPkInfo) Descriptor() ([]byte, []int) {
	return file_bed_type_proto_rawDescGZIP(), []int{0}
}

func (x *BedPkInfo) GetChallenger() *PlayerInfo {
	if x != nil {
		return x.Challenger
	}
	return nil
}

func (x *BedPkInfo) GetOwnerScore() int64 {
	if x != nil {
		return x.OwnerScore
	}
	return 0
}

func (x *BedPkInfo) GetChallengerScore() int64 {
	if x != nil {
		return x.ChallengerScore
	}
	return 0
}

func (x *BedPkInfo) GetTotalCountdown() uint32 {
	if x != nil {
		return x.TotalCountdown
	}
	return 0
}

func (x *BedPkInfo) GetOwnerSupporters() []*PlayerInfo {
	if x != nil {
		return x.OwnerSupporters
	}
	return nil
}

func (x *BedPkInfo) GetChallengerSupporters() []*PlayerInfo {
	if x != nil {
		return x.ChallengerSupporters
	}
	return nil
}

// BedInfo 床位实时业务状态
type BedInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PkInfo        *BedPkInfo             `protobuf:"bytes,1,opt,name=pk_info,json=pkInfo,proto3" json:"pk_info,omitempty"` // PK数据 (如果为空则非PK状态)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BedInfo) Reset() {
	*x = BedInfo{}
	mi := &file_bed_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BedInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BedInfo) ProtoMessage() {}

func (x *BedInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bed_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BedInfo.ProtoReflect.Descriptor instead.
func (*BedInfo) Descriptor() ([]byte, []int) {
	return file_bed_type_proto_rawDescGZIP(), []int{1}
}

func (x *BedInfo) GetPkInfo() *BedPkInfo {
	if x != nil {
		return x.PkInfo
	}
	return nil
}

var File_bed_type_proto protoreflect.FileDescriptor

const file_bed_type_proto_rawDesc = "" +
	"\n" +
	"\x0ebed_type.proto\x12\x04game\x1a\x11player_type.proto\"\xb6\x02\n" +
	"\tBedPkInfo\x120\n" +
	"\n" +
	"challenger\x18\x01 \x01(\v2\x10.game.PlayerInfoR\n" +
	"challenger\x12\x1f\n" +
	"\vowner_score\x18\x02 \x01(\x03R\n" +
	"ownerScore\x12)\n" +
	"\x10challenger_score\x18\x03 \x01(\x03R\x0fchallengerScore\x12'\n" +
	"\x0ftotal_countdown\x18\x04 \x01(\rR\x0etotalCountdown\x12;\n" +
	"\x10owner_supporters\x18\x05 \x03(\v2\x10.game.PlayerInfoR\x0fownerSupporters\x12E\n" +
	"\x15challenger_supporters\x18\x06 \x03(\v2\x10.game.PlayerInfoR\x14challengerSupporters\"3\n" +
	"\aBedInfo\x12(\n" +
	"\apk_info\x18\x01 \x01(\v2\x0f.game.BedPkInfoR\x06pkInfo*+\n" +
	"\tBedOpType\x12\x0e\n" +
	"\n" +
	"BED_OP_ADD\x10\x00\x12\x0e\n" +
	"\n" +
	"BED_OP_SUB\x10\x01*R\n" +
	"\fBedValueType\x12\x18\n" +
	"\x14BED_VALUE_PROTECTION\x10\x00\x12\x12\n" +
	"\x0eBED_VALUE_SEAL\x10\x01\x12\x14\n" +
	"\x10BED_VALUE_ENERGY\x10\x02B1Z/github.com/lk2023060901/xiaojia-proto-game;gameb\x06proto3"

var (
	file_bed_type_proto_rawDescOnce sync.Once
	file_bed_type_proto_rawDescData []byte
)

func file_bed_type_proto_rawDescGZIP() []byte {
	file_bed_type_proto_rawDescOnce.Do(func() {
		file_bed_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bed_type_proto_rawDesc), len(file_bed_type_proto_rawDesc)))
	})
	return file_bed_type_proto_rawDescData
}

var file_bed_type_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_bed_type_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bed_type_proto_goTypes = []any{
	(BedOpType)(0),     // 0: game.BedOpType
	(BedValueType)(0),  // 1: game.BedValueType
	(*BedPkInfo)(nil),  // 2: game.BedPkInfo
	(*BedInfo)(nil),    // 3: game.BedInfo
	(*PlayerInfo)(nil), // 4: game.PlayerInfo
}
var file_bed_type_proto_depIdxs = []int32{
	4, // 0: game.BedPkInfo.challenger:type_name -> game.PlayerInfo
	4, // 1: game.BedPkInfo.owner_supporters:type_name -> game.PlayerInfo
	4, // 2: game.BedPkInfo.challenger_supporters:type_name -> game.PlayerInfo
	2, // 3: game.BedInfo.pk_info:type_name -> game.BedPkInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_bed_type_proto_init() }
func file_bed_type_proto_init() {
	if File_bed_type_proto != nil {
		return
	}
	file_player_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bed_type_proto_rawDesc), len(file_bed_type_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bed_type_proto_goTypes,
		DependencyIndexes: file_bed_type_proto_depIdxs,
		EnumInfos:         file_bed_type_proto_enumTypes,
		MessageInfos:      file_bed_type_proto_msgTypes,
	}.Build()
	File_bed_type_proto = out.File
	file_bed_type_proto_goTypes = nil
	file_bed_type_proto_depIdxs = nil
}
