// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: client.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AnchorLoadCompletedReq 主播资源加载完成请求 [C2S]
type AnchorLoadCompletedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnchorLoadCompletedReq) Reset() {
	*x = AnchorLoadCompletedReq{}
	mi := &file_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnchorLoadCompletedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnchorLoadCompletedReq) ProtoMessage() {}

func (x *AnchorLoadCompletedReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnchorLoadCompletedReq.ProtoReflect.Descriptor instead.
func (*AnchorLoadCompletedReq) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{0}
}

// AnchorLoadCompletedRsp 主播资源加载完成响应 [S2C]
type AnchorLoadCompletedRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnchorLoadCompletedRsp) Reset() {
	*x = AnchorLoadCompletedRsp{}
	mi := &file_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnchorLoadCompletedRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnchorLoadCompletedRsp) ProtoMessage() {}

func (x *AnchorLoadCompletedRsp) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnchorLoadCompletedRsp.ProtoReflect.Descriptor instead.
func (*AnchorLoadCompletedRsp) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{1}
}

// PlayerLoadCompletedReq 玩家资源加载完成请求 [C2S]
type PlayerLoadCompletedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLoadCompletedReq) Reset() {
	*x = PlayerLoadCompletedReq{}
	mi := &file_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLoadCompletedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLoadCompletedReq) ProtoMessage() {}

func (x *PlayerLoadCompletedReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLoadCompletedReq.ProtoReflect.Descriptor instead.
func (*PlayerLoadCompletedReq) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{2}
}

// PlayerLoadCompletedRsp 玩家资源加载完成响应 [S2C]
type PlayerLoadCompletedRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLoadCompletedRsp) Reset() {
	*x = PlayerLoadCompletedRsp{}
	mi := &file_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLoadCompletedRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLoadCompletedRsp) ProtoMessage() {}

func (x *PlayerLoadCompletedRsp) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLoadCompletedRsp.ProtoReflect.Descriptor instead.
func (*PlayerLoadCompletedRsp) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{3}
}

// HeartbeatReq 心跳请求（Client -> Gateway）
type HeartbeatReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 客户端时间戳（毫秒）
	ClientTime    int64 `protobuf:"varint,1,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatReq) Reset() {
	*x = HeartbeatReq{}
	mi := &file_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReq) ProtoMessage() {}

func (x *HeartbeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReq.ProtoReflect.Descriptor instead.
func (*HeartbeatReq) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatReq) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

// HeartbeatRsp 心跳响应
type HeartbeatRsp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 客户端时间戳（毫秒，原样返回）
	ClientTime int64 `protobuf:"varint,1,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"`
	// 服务器时间戳（毫秒）
	ServerTime    int64 `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRsp) Reset() {
	*x = HeartbeatRsp{}
	mi := &file_client_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRsp) ProtoMessage() {}

func (x *HeartbeatRsp) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRsp.ProtoReflect.Descriptor instead.
func (*HeartbeatRsp) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatRsp) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

func (x *HeartbeatRsp) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

// ReconnectReq 断线重连请求（Client -> Gateway）
type ReconnectReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 登录获取的 Token
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconnectReq) Reset() {
	*x = ReconnectReq{}
	mi := &file_client_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconnectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconnectReq) ProtoMessage() {}

func (x *ReconnectReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconnectReq.ProtoReflect.Descriptor instead.
func (*ReconnectReq) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{6}
}

func (x *ReconnectReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// ReconnectRsp 断线重连响应
type ReconnectRsp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 错误码
	Code          ErrCode `protobuf:"varint,1,opt,name=code,proto3,enum=game.ErrCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconnectRsp) Reset() {
	*x = ReconnectRsp{}
	mi := &file_client_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconnectRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconnectRsp) ProtoMessage() {}

func (x *ReconnectRsp) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconnectRsp.ProtoReflect.Descriptor instead.
func (*ReconnectRsp) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{7}
}

func (x *ReconnectRsp) GetCode() ErrCode {
	if x != nil {
		return x.Code
	}
	return ErrCode_ERR_SUCCESS
}

// InitAnchorRoomReq 初始化主播房间请求（内部使用）
type InitAnchorRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitAnchorRoomReq) Reset() {
	*x = InitAnchorRoomReq{}
	mi := &file_client_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitAnchorRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitAnchorRoomReq) ProtoMessage() {}

func (x *InitAnchorRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitAnchorRoomReq.ProtoReflect.Descriptor instead.
func (*InitAnchorRoomReq) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{8}
}

var File_client_proto protoreflect.FileDescriptor

const file_client_proto_rawDesc = "" +
	"\n" +
	"\fclient.proto\x12\x04game\x1a\x0eerr_code.proto\"\x18\n" +
	"\x16AnchorLoadCompletedReq\"\x18\n" +
	"\x16AnchorLoadCompletedRsp\"\x18\n" +
	"\x16PlayerLoadCompletedReq\"\x18\n" +
	"\x16PlayerLoadCompletedRsp\"/\n" +
	"\fHeartbeatReq\x12\x1f\n" +
	"\vclient_time\x18\x01 \x01(\x03R\n" +
	"clientTime\"P\n" +
	"\fHeartbeatRsp\x12\x1f\n" +
	"\vclient_time\x18\x01 \x01(\x03R\n" +
	"clientTime\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\"$\n" +
	"\fReconnectReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"1\n" +
	"\fReconnectRsp\x12!\n" +
	"\x04code\x18\x01 \x01(\x0e2\r.game.ErrCodeR\x04code\"\x13\n" +
	"\x11InitAnchorRoomReqB1Z/github.com/lk2023060901/xiaojia-proto-game;gameb\x06proto3"

var (
	file_client_proto_rawDescOnce sync.Once
	file_client_proto_rawDescData []byte
)

func file_client_proto_rawDescGZIP() []byte {
	file_client_proto_rawDescOnce.Do(func() {
		file_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_proto_rawDesc), len(file_client_proto_rawDesc)))
	})
	return file_client_proto_rawDescData
}

var file_client_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_client_proto_goTypes = []any{
	(*AnchorLoadCompletedReq)(nil), // 0: game.AnchorLoadCompletedReq
	(*AnchorLoadCompletedRsp)(nil), // 1: game.AnchorLoadCompletedRsp
	(*PlayerLoadCompletedReq)(nil), // 2: game.PlayerLoadCompletedReq
	(*PlayerLoadCompletedRsp)(nil), // 3: game.PlayerLoadCompletedRsp
	(*HeartbeatReq)(nil),           // 4: game.HeartbeatReq
	(*HeartbeatRsp)(nil),           // 5: game.HeartbeatRsp
	(*ReconnectReq)(nil),           // 6: game.ReconnectReq
	(*ReconnectRsp)(nil),           // 7: game.ReconnectRsp
	(*InitAnchorRoomReq)(nil),      // 8: game.InitAnchorRoomReq
	(ErrCode)(0),                   // 9: game.ErrCode
}
var file_client_proto_depIdxs = []int32{
	9, // 0: game.ReconnectRsp.code:type_name -> game.ErrCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_client_proto_init() }
func file_client_proto_init() {
	if File_client_proto != nil {
		return
	}
	file_err_code_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_proto_rawDesc), len(file_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_proto_goTypes,
		DependencyIndexes: file_client_proto_depIdxs,
		MessageInfos:      file_client_proto_msgTypes,
	}.Build()
	File_client_proto = out.File
	file_client_proto_goTypes = nil
	file_client_proto_depIdxs = nil
}
