// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: competition_type.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CompStageType 竞赛阶段类型
type CompStageType int32

const (
	CompStageType_COMP_STAGE_NONE       CompStageType = 0
	CompStageType_COMP_STAGE_SIGNUP     CompStageType = 1 // 报名阶段
	CompStageType_COMP_STAGE_VOTING     CompStageType = 2 // 投票阶段 (选奖品)
	CompStageType_COMP_STAGE_PK         CompStageType = 3 // PK阶段 (抢擂台)
	CompStageType_COMP_STAGE_SETTLEMENT CompStageType = 4 // 结算阶段
)

// Enum value maps for CompStageType.
var (
	CompStageType_name = map[int32]string{
		0: "COMP_STAGE_NONE",
		1: "COMP_STAGE_SIGNUP",
		2: "COMP_STAGE_VOTING",
		3: "COMP_STAGE_PK",
		4: "COMP_STAGE_SETTLEMENT",
	}
	CompStageType_value = map[string]int32{
		"COMP_STAGE_NONE":       0,
		"COMP_STAGE_SIGNUP":     1,
		"COMP_STAGE_VOTING":     2,
		"COMP_STAGE_PK":         3,
		"COMP_STAGE_SETTLEMENT": 4,
	}
)

func (x CompStageType) Enum() *CompStageType {
	p := new(CompStageType)
	*p = x
	return p
}

func (x CompStageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompStageType) Descriptor() protoreflect.EnumDescriptor {
	return file_competition_type_proto_enumTypes[0].Descriptor()
}

func (CompStageType) Type() protoreflect.EnumType {
	return &file_competition_type_proto_enumTypes[0]
}

func (x CompStageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompStageType.Descriptor instead.
func (CompStageType) EnumDescriptor() ([]byte, []int) {
	return file_competition_type_proto_rawDescGZIP(), []int{0}
}

// CompSide 竞赛 PK 阵营
type CompSide int32

const (
	CompSide_COMP_SIDE_NONE       CompSide = 0
	CompSide_COMP_SIDE_OWNER      CompSide = 1 // 擂主方
	CompSide_COMP_SIDE_CHALLENGER CompSide = 2 // 挑战者方
)

// Enum value maps for CompSide.
var (
	CompSide_name = map[int32]string{
		0: "COMP_SIDE_NONE",
		1: "COMP_SIDE_OWNER",
		2: "COMP_SIDE_CHALLENGER",
	}
	CompSide_value = map[string]int32{
		"COMP_SIDE_NONE":       0,
		"COMP_SIDE_OWNER":      1,
		"COMP_SIDE_CHALLENGER": 2,
	}
)

func (x CompSide) Enum() *CompSide {
	p := new(CompSide)
	*p = x
	return p
}

func (x CompSide) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompSide) Descriptor() protoreflect.EnumDescriptor {
	return file_competition_type_proto_enumTypes[1].Descriptor()
}

func (CompSide) Type() protoreflect.EnumType {
	return &file_competition_type_proto_enumTypes[1]
}

func (x CompSide) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompSide.Descriptor instead.
func (CompSide) EnumDescriptor() ([]byte, []int) {
	return file_competition_type_proto_rawDescGZIP(), []int{1}
}

// CompVoteItem 竞赛投票候选项
type CompVoteItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OptionId      uint32                 `protobuf:"varint,1,opt,name=option_id,json=optionId,proto3" json:"option_id,omitempty"`    // 选项编号 (1, 2, 3...)
	ItemId        uint32                 `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`          // 奖品道具ID
	VoteCount     uint32                 `protobuf:"varint,3,opt,name=vote_count,json=voteCount,proto3" json:"vote_count,omitempty"` // 当前累计票数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompVoteItem) Reset() {
	*x = CompVoteItem{}
	mi := &file_competition_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompVoteItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompVoteItem) ProtoMessage() {}

func (x *CompVoteItem) ProtoReflect() protoreflect.Message {
	mi := &file_competition_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompVoteItem.ProtoReflect.Descriptor instead.
func (*CompVoteItem) Descriptor() ([]byte, []int) {
	return file_competition_type_proto_rawDescGZIP(), []int{0}
}

func (x *CompVoteItem) GetOptionId() uint32 {
	if x != nil {
		return x.OptionId
	}
	return 0
}

func (x *CompVoteItem) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *CompVoteItem) GetVoteCount() uint32 {
	if x != nil {
		return x.VoteCount
	}
	return 0
}

// CompArenaInfo 竞赛擂台实时状态
type CompArenaInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Owner           *PlayerInfo            `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`                                             // 当前擂主
	Challenger      *PlayerInfo            `protobuf:"bytes,2,opt,name=challenger,proto3" json:"challenger,omitempty"`                                   // 当前挑战者
	OwnerScore      int64                  `protobuf:"varint,3,opt,name=owner_score,json=ownerScore,proto3" json:"owner_score,omitempty"`                // 擂主积分
	ChallengerScore int64                  `protobuf:"varint,4,opt,name=challenger_score,json=challengerScore,proto3" json:"challenger_score,omitempty"` // 挑战者积分
	PkCountdown     uint32                 `protobuf:"varint,5,opt,name=pk_countdown,json=pkCountdown,proto3" json:"pk_countdown,omitempty"`             // 当前这一场PK的无人抢占倒计时
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CompArenaInfo) Reset() {
	*x = CompArenaInfo{}
	mi := &file_competition_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompArenaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompArenaInfo) ProtoMessage() {}

func (x *CompArenaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_competition_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompArenaInfo.ProtoReflect.Descriptor instead.
func (*CompArenaInfo) Descriptor() ([]byte, []int) {
	return file_competition_type_proto_rawDescGZIP(), []int{1}
}

func (x *CompArenaInfo) GetOwner() *PlayerInfo {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *CompArenaInfo) GetChallenger() *PlayerInfo {
	if x != nil {
		return x.Challenger
	}
	return nil
}

func (x *CompArenaInfo) GetOwnerScore() int64 {
	if x != nil {
		return x.OwnerScore
	}
	return 0
}

func (x *CompArenaInfo) GetChallengerScore() int64 {
	if x != nil {
		return x.ChallengerScore
	}
	return 0
}

func (x *CompArenaInfo) GetPkCountdown() uint32 {
	if x != nil {
		return x.PkCountdown
	}
	return 0
}

var File_competition_type_proto protoreflect.FileDescriptor

const file_competition_type_proto_rawDesc = "" +
	"\n" +
	"\x16competition_type.proto\x12\x04game\x1a\x11player_type.proto\"c\n" +
	"\fCompVoteItem\x12\x1b\n" +
	"\toption_id\x18\x01 \x01(\rR\boptionId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\rR\x06itemId\x12\x1d\n" +
	"\n" +
	"vote_count\x18\x03 \x01(\rR\tvoteCount\"\xd8\x01\n" +
	"\rCompArenaInfo\x12&\n" +
	"\x05owner\x18\x01 \x01(\v2\x10.game.PlayerInfoR\x05owner\x120\n" +
	"\n" +
	"challenger\x18\x02 \x01(\v2\x10.game.PlayerInfoR\n" +
	"challenger\x12\x1f\n" +
	"\vowner_score\x18\x03 \x01(\x03R\n" +
	"ownerScore\x12)\n" +
	"\x10challenger_score\x18\x04 \x01(\x03R\x0fchallengerScore\x12!\n" +
	"\fpk_countdown\x18\x05 \x01(\rR\vpkCountdown*\x80\x01\n" +
	"\rCompStageType\x12\x13\n" +
	"\x0fCOMP_STAGE_NONE\x10\x00\x12\x15\n" +
	"\x11COMP_STAGE_SIGNUP\x10\x01\x12\x15\n" +
	"\x11COMP_STAGE_VOTING\x10\x02\x12\x11\n" +
	"\rCOMP_STAGE_PK\x10\x03\x12\x19\n" +
	"\x15COMP_STAGE_SETTLEMENT\x10\x04*M\n" +
	"\bCompSide\x12\x12\n" +
	"\x0eCOMP_SIDE_NONE\x10\x00\x12\x13\n" +
	"\x0fCOMP_SIDE_OWNER\x10\x01\x12\x18\n" +
	"\x14COMP_SIDE_CHALLENGER\x10\x02B1Z/github.com/lk2023060901/xiaojia-proto-game;gameb\x06proto3"

var (
	file_competition_type_proto_rawDescOnce sync.Once
	file_competition_type_proto_rawDescData []byte
)

func file_competition_type_proto_rawDescGZIP() []byte {
	file_competition_type_proto_rawDescOnce.Do(func() {
		file_competition_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_competition_type_proto_rawDesc), len(file_competition_type_proto_rawDesc)))
	})
	return file_competition_type_proto_rawDescData
}

var file_competition_type_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_competition_type_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_competition_type_proto_goTypes = []any{
	(CompStageType)(0),    // 0: game.CompStageType
	(CompSide)(0),         // 1: game.CompSide
	(*CompVoteItem)(nil),  // 2: game.CompVoteItem
	(*CompArenaInfo)(nil), // 3: game.CompArenaInfo
	(*PlayerInfo)(nil),    // 4: game.PlayerInfo
}
var file_competition_type_proto_depIdxs = []int32{
	4, // 0: game.CompArenaInfo.owner:type_name -> game.PlayerInfo
	4, // 1: game.CompArenaInfo.challenger:type_name -> game.PlayerInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_competition_type_proto_init() }
func file_competition_type_proto_init() {
	if File_competition_type_proto != nil {
		return
	}
	file_player_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_competition_type_proto_rawDesc), len(file_competition_type_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_competition_type_proto_goTypes,
		DependencyIndexes: file_competition_type_proto_depIdxs,
		EnumInfos:         file_competition_type_proto_enumTypes,
		MessageInfos:      file_competition_type_proto_msgTypes,
	}.Build()
	File_competition_type_proto = out.File
	file_competition_type_proto_goTypes = nil
	file_competition_type_proto_depIdxs = nil
}
