// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: competition.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SyncCompVoting [S2C] 全量同步竞赛投票阶段数据
type SyncCompVoting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CompVoteItem        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`                                       // 候选奖品列表
	CountdownSecs uint32                 `protobuf:"varint,2,opt,name=countdown_secs,json=countdownSecs,proto3" json:"countdown_secs,omitempty"` // 投票剩余秒数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncCompVoting) Reset() {
	*x = SyncCompVoting{}
	mi := &file_competition_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncCompVoting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncCompVoting) ProtoMessage() {}

func (x *SyncCompVoting) ProtoReflect() protoreflect.Message {
	mi := &file_competition_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncCompVoting.ProtoReflect.Descriptor instead.
func (*SyncCompVoting) Descriptor() ([]byte, []int) {
	return file_competition_proto_rawDescGZIP(), []int{0}
}

func (x *SyncCompVoting) GetItems() []*CompVoteItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SyncCompVoting) GetCountdownSecs() uint32 {
	if x != nil {
		return x.CountdownSecs
	}
	return 0
}

// SyncCompVoteUpdate [S2C] 增量同步票数变动
type SyncCompVoteUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OptionId      uint32                 `protobuf:"varint,1,opt,name=option_id,json=optionId,proto3" json:"option_id,omitempty"`    // 变化的选项编号
	VoteCount     uint32                 `protobuf:"varint,2,opt,name=vote_count,json=voteCount,proto3" json:"vote_count,omitempty"` // 最新累计票数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncCompVoteUpdate) Reset() {
	*x = SyncCompVoteUpdate{}
	mi := &file_competition_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncCompVoteUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncCompVoteUpdate) ProtoMessage() {}

func (x *SyncCompVoteUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_competition_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncCompVoteUpdate.ProtoReflect.Descriptor instead.
func (*SyncCompVoteUpdate) Descriptor() ([]byte, []int) {
	return file_competition_proto_rawDescGZIP(), []int{1}
}

func (x *SyncCompVoteUpdate) GetOptionId() uint32 {
	if x != nil {
		return x.OptionId
	}
	return 0
}

func (x *SyncCompVoteUpdate) GetVoteCount() uint32 {
	if x != nil {
		return x.VoteCount
	}
	return 0
}

// SyncCompStage [S2C] 阶段切换同步
type SyncCompStage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         CompStageType          `protobuf:"varint,1,opt,name=stage,proto3,enum=game.CompStageType" json:"stage,omitempty"`              // 当前进入的阶段
	CountdownSecs uint32                 `protobuf:"varint,2,opt,name=countdown_secs,json=countdownSecs,proto3" json:"countdown_secs,omitempty"` // 该阶段剩余总时长
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncCompStage) Reset() {
	*x = SyncCompStage{}
	mi := &file_competition_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncCompStage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncCompStage) ProtoMessage() {}

func (x *SyncCompStage) ProtoReflect() protoreflect.Message {
	mi := &file_competition_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncCompStage.ProtoReflect.Descriptor instead.
func (*SyncCompStage) Descriptor() ([]byte, []int) {
	return file_competition_proto_rawDescGZIP(), []int{2}
}

func (x *SyncCompStage) GetStage() CompStageType {
	if x != nil {
		return x.Stage
	}
	return CompStageType_COMP_STAGE_NONE
}

func (x *SyncCompStage) GetCountdownSecs() uint32 {
	if x != nil {
		return x.CountdownSecs
	}
	return 0
}

// SyncCompSignup [S2C] 报名阶段助力同步
type SyncCompSignup struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CurrentAnchorScore int64                  `protobuf:"varint,1,opt,name=current_anchor_score,json=currentAnchorScore,proto3" json:"current_anchor_score,omitempty"` // 当前主播获得的助力总分
	CurrentRank        uint32                 `protobuf:"varint,2,opt,name=current_rank,json=currentRank,proto3" json:"current_rank,omitempty"`                        // 当前主播在全服的排名
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SyncCompSignup) Reset() {
	*x = SyncCompSignup{}
	mi := &file_competition_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncCompSignup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncCompSignup) ProtoMessage() {}

func (x *SyncCompSignup) ProtoReflect() protoreflect.Message {
	mi := &file_competition_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncCompSignup.ProtoReflect.Descriptor instead.
func (*SyncCompSignup) Descriptor() ([]byte, []int) {
	return file_competition_proto_rawDescGZIP(), []int{3}
}

func (x *SyncCompSignup) GetCurrentAnchorScore() int64 {
	if x != nil {
		return x.CurrentAnchorScore
	}
	return 0
}

func (x *SyncCompSignup) GetCurrentRank() uint32 {
	if x != nil {
		return x.CurrentRank
	}
	return 0
}

// SyncCompPk [S2C] PK阶段状态全量同步
type SyncCompPk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Arena         *CompArenaInfo         `protobuf:"bytes,1,opt,name=arena,proto3" json:"arena,omitempty"` // 擂台详细细节
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncCompPk) Reset() {
	*x = SyncCompPk{}
	mi := &file_competition_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncCompPk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncCompPk) ProtoMessage() {}

func (x *SyncCompPk) ProtoReflect() protoreflect.Message {
	mi := &file_competition_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncCompPk.ProtoReflect.Descriptor instead.
func (*SyncCompPk) Descriptor() ([]byte, []int) {
	return file_competition_proto_rawDescGZIP(), []int{4}
}

func (x *SyncCompPk) GetArena() *CompArenaInfo {
	if x != nil {
		return x.Arena
	}
	return nil
}

// SyncCompPkScore [S2C] 增量同步 PK 阵营积分变动
type SyncCompPkScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Side          CompSide               `protobuf:"varint,1,opt,name=side,proto3,enum=game.CompSide" json:"side,omitempty"`                  // 哪一方增加积分
	CurrentScore  int64                  `protobuf:"varint,2,opt,name=current_score,json=currentScore,proto3" json:"current_score,omitempty"` // 最新的累计总积分
	AddAmount     int64                  `protobuf:"varint,3,opt,name=add_amount,json=addAmount,proto3" json:"add_amount,omitempty"`          // 本次增加的数值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncCompPkScore) Reset() {
	*x = SyncCompPkScore{}
	mi := &file_competition_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncCompPkScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncCompPkScore) ProtoMessage() {}

func (x *SyncCompPkScore) ProtoReflect() protoreflect.Message {
	mi := &file_competition_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncCompPkScore.ProtoReflect.Descriptor instead.
func (*SyncCompPkScore) Descriptor() ([]byte, []int) {
	return file_competition_proto_rawDescGZIP(), []int{5}
}

func (x *SyncCompPkScore) GetSide() CompSide {
	if x != nil {
		return x.Side
	}
	return CompSide_COMP_SIDE_NONE
}

func (x *SyncCompPkScore) GetCurrentScore() int64 {
	if x != nil {
		return x.CurrentScore
	}
	return 0
}

func (x *SyncCompPkScore) GetAddAmount() int64 {
	if x != nil {
		return x.AddAmount
	}
	return 0
}

// SyncCompSettlement [S2C] 结算阶段同步
type SyncCompSettlement struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Winner           *PlayerInfo            `protobuf:"bytes,1,opt,name=winner,proto3" json:"winner,omitempty"`                                               // 获胜玩家 (擂主)
	WinnerAnchorName string                 `protobuf:"bytes,2,opt,name=winner_anchor_name,json=winnerAnchorName,proto3" json:"winner_anchor_name,omitempty"` // 获胜主播名称
	PrizeItemId      uint32                 `protobuf:"varint,3,opt,name=prize_item_id,json=prizeItemId,proto3" json:"prize_item_id,omitempty"`               // 主播获得的奖品ID
	TotalEnergyCost  int64                  `protobuf:"varint,4,opt,name=total_energy_cost,json=totalEnergyCost,proto3" json:"total_energy_cost,omitempty"`   // 本场直播间累积消耗的装饰能量
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncCompSettlement) Reset() {
	*x = SyncCompSettlement{}
	mi := &file_competition_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncCompSettlement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncCompSettlement) ProtoMessage() {}

func (x *SyncCompSettlement) ProtoReflect() protoreflect.Message {
	mi := &file_competition_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncCompSettlement.ProtoReflect.Descriptor instead.
func (*SyncCompSettlement) Descriptor() ([]byte, []int) {
	return file_competition_proto_rawDescGZIP(), []int{6}
}

func (x *SyncCompSettlement) GetWinner() *PlayerInfo {
	if x != nil {
		return x.Winner
	}
	return nil
}

func (x *SyncCompSettlement) GetWinnerAnchorName() string {
	if x != nil {
		return x.WinnerAnchorName
	}
	return ""
}

func (x *SyncCompSettlement) GetPrizeItemId() uint32 {
	if x != nil {
		return x.PrizeItemId
	}
	return 0
}

func (x *SyncCompSettlement) GetTotalEnergyCost() int64 {
	if x != nil {
		return x.TotalEnergyCost
	}
	return 0
}

var File_competition_proto protoreflect.FileDescriptor

const file_competition_proto_rawDesc = "" +
	"\n" +
	"\x11competition.proto\x12\x04game\x1a\x16competition_type.proto\x1a\x11player_type.proto\"a\n" +
	"\x0eSyncCompVoting\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.game.CompVoteItemR\x05items\x12%\n" +
	"\x0ecountdown_secs\x18\x02 \x01(\rR\rcountdownSecs\"P\n" +
	"\x12SyncCompVoteUpdate\x12\x1b\n" +
	"\toption_id\x18\x01 \x01(\rR\boptionId\x12\x1d\n" +
	"\n" +
	"vote_count\x18\x02 \x01(\rR\tvoteCount\"a\n" +
	"\rSyncCompStage\x12)\n" +
	"\x05stage\x18\x01 \x01(\x0e2\x13.game.CompStageTypeR\x05stage\x12%\n" +
	"\x0ecountdown_secs\x18\x02 \x01(\rR\rcountdownSecs\"e\n" +
	"\x0eSyncCompSignup\x120\n" +
	"\x14current_anchor_score\x18\x01 \x01(\x03R\x12currentAnchorScore\x12!\n" +
	"\fcurrent_rank\x18\x02 \x01(\rR\vcurrentRank\"7\n" +
	"\n" +
	"SyncCompPk\x12)\n" +
	"\x05arena\x18\x01 \x01(\v2\x13.game.CompArenaInfoR\x05arena\"y\n" +
	"\x0fSyncCompPkScore\x12\"\n" +
	"\x04side\x18\x01 \x01(\x0e2\x0e.game.CompSideR\x04side\x12#\n" +
	"\rcurrent_score\x18\x02 \x01(\x03R\fcurrentScore\x12\x1d\n" +
	"\n" +
	"add_amount\x18\x03 \x01(\x03R\taddAmount\"\xbc\x01\n" +
	"\x12SyncCompSettlement\x12(\n" +
	"\x06winner\x18\x01 \x01(\v2\x10.game.PlayerInfoR\x06winner\x12,\n" +
	"\x12winner_anchor_name\x18\x02 \x01(\tR\x10winnerAnchorName\x12\"\n" +
	"\rprize_item_id\x18\x03 \x01(\rR\vprizeItemId\x12*\n" +
	"\x11total_energy_cost\x18\x04 \x01(\x03R\x0ftotalEnergyCostB1Z/github.com/lk2023060901/xiaojia-proto-game;gameb\x06proto3"

var (
	file_competition_proto_rawDescOnce sync.Once
	file_competition_proto_rawDescData []byte
)

func file_competition_proto_rawDescGZIP() []byte {
	file_competition_proto_rawDescOnce.Do(func() {
		file_competition_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_competition_proto_rawDesc), len(file_competition_proto_rawDesc)))
	})
	return file_competition_proto_rawDescData
}

var file_competition_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_competition_proto_goTypes = []any{
	(*SyncCompVoting)(nil),     // 0: game.SyncCompVoting
	(*SyncCompVoteUpdate)(nil), // 1: game.SyncCompVoteUpdate
	(*SyncCompStage)(nil),      // 2: game.SyncCompStage
	(*SyncCompSignup)(nil),     // 3: game.SyncCompSignup
	(*SyncCompPk)(nil),         // 4: game.SyncCompPk
	(*SyncCompPkScore)(nil),    // 5: game.SyncCompPkScore
	(*SyncCompSettlement)(nil), // 6: game.SyncCompSettlement
	(*CompVoteItem)(nil),       // 7: game.CompVoteItem
	(CompStageType)(0),         // 8: game.CompStageType
	(*CompArenaInfo)(nil),      // 9: game.CompArenaInfo
	(CompSide)(0),              // 10: game.CompSide
	(*PlayerInfo)(nil),         // 11: game.PlayerInfo
}
var file_competition_proto_depIdxs = []int32{
	7,  // 0: game.SyncCompVoting.items:type_name -> game.CompVoteItem
	8,  // 1: game.SyncCompStage.stage:type_name -> game.CompStageType
	9,  // 2: game.SyncCompPk.arena:type_name -> game.CompArenaInfo
	10, // 3: game.SyncCompPkScore.side:type_name -> game.CompSide
	11, // 4: game.SyncCompSettlement.winner:type_name -> game.PlayerInfo
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_competition_proto_init() }
func file_competition_proto_init() {
	if File_competition_proto != nil {
		return
	}
	file_competition_type_proto_init()
	file_player_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_competition_proto_rawDesc), len(file_competition_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_competition_proto_goTypes,
		DependencyIndexes: file_competition_proto_depIdxs,
		MessageInfos:      file_competition_proto_msgTypes,
	}.Build()
	File_competition_proto = out.File
	file_competition_proto_goTypes = nil
	file_competition_proto_depIdxs = nil
}
