// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: err_code.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrCode 错误码定义
//
// 号段分配规则：
//   - 每个玩法保留 1000 个号段
//   - 0-999: 系统保留
type ErrCode int32

const (
	// ============================================================
	// 系统保留 (0-999)
	// ============================================================
	ErrCode_ERR_SUCCESS       ErrCode = 0
	ErrCode_ERR_UNKNOWN       ErrCode = 1
	ErrCode_ERR_INTERNAL      ErrCode = 2
	ErrCode_ERR_INVALID_PARAM ErrCode = 3
	// 认证错误
	ErrCode_ERR_AUTH_FAILED   ErrCode = 10
	ErrCode_ERR_TOKEN_INVALID ErrCode = 11
	ErrCode_ERR_TOKEN_EXPIRED ErrCode = 12
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0:  "ERR_SUCCESS",
		1:  "ERR_UNKNOWN",
		2:  "ERR_INTERNAL",
		3:  "ERR_INVALID_PARAM",
		10: "ERR_AUTH_FAILED",
		11: "ERR_TOKEN_INVALID",
		12: "ERR_TOKEN_EXPIRED",
	}
	ErrCode_value = map[string]int32{
		"ERR_SUCCESS":       0,
		"ERR_UNKNOWN":       1,
		"ERR_INTERNAL":      2,
		"ERR_INVALID_PARAM": 3,
		"ERR_AUTH_FAILED":   10,
		"ERR_TOKEN_INVALID": 11,
		"ERR_TOKEN_EXPIRED": 12,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_err_code_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_err_code_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_err_code_proto_rawDescGZIP(), []int{0}
}

var File_err_code_proto protoreflect.FileDescriptor

const file_err_code_proto_rawDesc = "" +
	"\n" +
	"\x0eerr_code.proto\x12\x04game*\x97\x01\n" +
	"\aErrCode\x12\x0f\n" +
	"\vERR_SUCCESS\x10\x00\x12\x0f\n" +
	"\vERR_UNKNOWN\x10\x01\x12\x10\n" +
	"\fERR_INTERNAL\x10\x02\x12\x15\n" +
	"\x11ERR_INVALID_PARAM\x10\x03\x12\x13\n" +
	"\x0fERR_AUTH_FAILED\x10\n" +
	"\x12\x15\n" +
	"\x11ERR_TOKEN_INVALID\x10\v\x12\x15\n" +
	"\x11ERR_TOKEN_EXPIRED\x10\fB1Z/github.com/lk2023060901/xiaojia-proto-game;gameb\x06proto3"

var (
	file_err_code_proto_rawDescOnce sync.Once
	file_err_code_proto_rawDescData []byte
)

func file_err_code_proto_rawDescGZIP() []byte {
	file_err_code_proto_rawDescOnce.Do(func() {
		file_err_code_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_err_code_proto_rawDesc), len(file_err_code_proto_rawDesc)))
	})
	return file_err_code_proto_rawDescData
}

var file_err_code_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_err_code_proto_goTypes = []any{
	(ErrCode)(0), // 0: game.ErrCode
}
var file_err_code_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_err_code_proto_init() }
func file_err_code_proto_init() {
	if File_err_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_err_code_proto_rawDesc), len(file_err_code_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_err_code_proto_goTypes,
		DependencyIndexes: file_err_code_proto_depIdxs,
		EnumInfos:         file_err_code_proto_enumTypes,
	}.Build()
	File_err_code_proto = out.File
	file_err_code_proto_goTypes = nil
	file_err_code_proto_depIdxs = nil
}
