// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: farming.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SyncFarmingRound [S2C] 种田轮次信息同步 (包含赔率和倒计时)
type SyncFarmingRound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Odds          []*FruitOdds           `protobuf:"bytes,1,rep,name=odds,proto3" json:"odds,omitempty"`                                         // 4种水果的实时赔率列表
	CountdownSecs uint32                 `protobuf:"varint,2,opt,name=countdown_secs,json=countdownSecs,proto3" json:"countdown_secs,omitempty"` // 距离开奖剩余秒数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncFarmingRound) Reset() {
	*x = SyncFarmingRound{}
	mi := &file_farming_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncFarmingRound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncFarmingRound) ProtoMessage() {}

func (x *SyncFarmingRound) ProtoReflect() protoreflect.Message {
	mi := &file_farming_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncFarmingRound.ProtoReflect.Descriptor instead.
func (*SyncFarmingRound) Descriptor() ([]byte, []int) {
	return file_farming_proto_rawDescGZIP(), []int{0}
}

func (x *SyncFarmingRound) GetOdds() []*FruitOdds {
	if x != nil {
		return x.Odds
	}
	return nil
}

func (x *SyncFarmingRound) GetCountdownSecs() uint32 {
	if x != nil {
		return x.CountdownSecs
	}
	return 0
}

// SyncFarmingField [S2C] 同步某个槽位上某个玩家某块田的变更
type SyncFarmingField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                     // 玩家UID
	SlotId        uint32                 `protobuf:"varint,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"` // 槽位编号 (1-9)
	Field         *FieldState            `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"`                  // 变更后的田块状态详情
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncFarmingField) Reset() {
	*x = SyncFarmingField{}
	mi := &file_farming_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncFarmingField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncFarmingField) ProtoMessage() {}

func (x *SyncFarmingField) ProtoReflect() protoreflect.Message {
	mi := &file_farming_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncFarmingField.ProtoReflect.Descriptor instead.
func (*SyncFarmingField) Descriptor() ([]byte, []int) {
	return file_farming_proto_rawDescGZIP(), []int{1}
}

func (x *SyncFarmingField) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SyncFarmingField) GetSlotId() uint32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *SyncFarmingField) GetField() *FieldState {
	if x != nil {
		return x.Field
	}
	return nil
}

// PlantingReq [C2S] 种植请求
type PlantingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         *FieldState            `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"` // 种植信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlantingReq) Reset() {
	*x = PlantingReq{}
	mi := &file_farming_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlantingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlantingReq) ProtoMessage() {}

func (x *PlantingReq) ProtoReflect() protoreflect.Message {
	mi := &file_farming_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlantingReq.ProtoReflect.Descriptor instead.
func (*PlantingReq) Descriptor() ([]byte, []int) {
	return file_farming_proto_rawDescGZIP(), []int{2}
}

func (x *PlantingReq) GetField() *FieldState {
	if x != nil {
		return x.Field
	}
	return nil
}

// PlantingRes [S2C] 种植响应
type PlantingRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrCode                `protobuf:"varint,1,opt,name=code,proto3,enum=game.ErrCode" json:"code,omitempty"` // 错误码
	Field         *FieldState            `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`                  // 种植成功后的信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlantingRes) Reset() {
	*x = PlantingRes{}
	mi := &file_farming_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlantingRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlantingRes) ProtoMessage() {}

func (x *PlantingRes) ProtoReflect() protoreflect.Message {
	mi := &file_farming_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlantingRes.ProtoReflect.Descriptor instead.
func (*PlantingRes) Descriptor() ([]byte, []int) {
	return file_farming_proto_rawDescGZIP(), []int{3}
}

func (x *PlantingRes) GetCode() ErrCode {
	if x != nil {
		return x.Code
	}
	return ErrCode_ERR_SUCCESS
}

func (x *PlantingRes) GetField() *FieldState {
	if x != nil {
		return x.Field
	}
	return nil
}

var File_farming_proto protoreflect.FileDescriptor

const file_farming_proto_rawDesc = "" +
	"\n" +
	"\rfarming.proto\x12\x04game\x1a\x12farming_type.proto\x1a\x0eerr_code.proto\"^\n" +
	"\x10SyncFarmingRound\x12#\n" +
	"\x04odds\x18\x01 \x03(\v2\x0f.game.FruitOddsR\x04odds\x12%\n" +
	"\x0ecountdown_secs\x18\x02 \x01(\rR\rcountdownSecs\"e\n" +
	"\x10SyncFarmingField\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x17\n" +
	"\aslot_id\x18\x02 \x01(\rR\x06slotId\x12&\n" +
	"\x05field\x18\x03 \x01(\v2\x10.game.FieldStateR\x05field\"5\n" +
	"\vPlantingReq\x12&\n" +
	"\x05field\x18\x01 \x01(\v2\x10.game.FieldStateR\x05field\"X\n" +
	"\vPlantingRes\x12!\n" +
	"\x04code\x18\x01 \x01(\x0e2\r.game.ErrCodeR\x04code\x12&\n" +
	"\x05field\x18\x02 \x01(\v2\x10.game.FieldStateR\x05fieldB1Z/github.com/lk2023060901/xiaojia-proto-game;gameb\x06proto3"

var (
	file_farming_proto_rawDescOnce sync.Once
	file_farming_proto_rawDescData []byte
)

func file_farming_proto_rawDescGZIP() []byte {
	file_farming_proto_rawDescOnce.Do(func() {
		file_farming_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_farming_proto_rawDesc), len(file_farming_proto_rawDesc)))
	})
	return file_farming_proto_rawDescData
}

var file_farming_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_farming_proto_goTypes = []any{
	(*SyncFarmingRound)(nil), // 0: game.SyncFarmingRound
	(*SyncFarmingField)(nil), // 1: game.SyncFarmingField
	(*PlantingReq)(nil),      // 2: game.PlantingReq
	(*PlantingRes)(nil),      // 3: game.PlantingRes
	(*FruitOdds)(nil),        // 4: game.FruitOdds
	(*FieldState)(nil),       // 5: game.FieldState
	(ErrCode)(0),             // 6: game.ErrCode
}
var file_farming_proto_depIdxs = []int32{
	4, // 0: game.SyncFarmingRound.odds:type_name -> game.FruitOdds
	5, // 1: game.SyncFarmingField.field:type_name -> game.FieldState
	5, // 2: game.PlantingReq.field:type_name -> game.FieldState
	6, // 3: game.PlantingRes.code:type_name -> game.ErrCode
	5, // 4: game.PlantingRes.field:type_name -> game.FieldState
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_farming_proto_init() }
func file_farming_proto_init() {
	if File_farming_proto != nil {
		return
	}
	file_farming_type_proto_init()
	file_err_code_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_farming_proto_rawDesc), len(file_farming_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_farming_proto_goTypes,
		DependencyIndexes: file_farming_proto_depIdxs,
		MessageInfos:      file_farming_proto_msgTypes,
	}.Build()
	File_farming_proto = out.File
	file_farming_proto_goTypes = nil
	file_farming_proto_depIdxs = nil
}
