// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: farming_type.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FruitOdds 单个水果的实时赔率
type FruitOdds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        uint32                 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"` // 水果道具ID
	Multiplier    float32                `protobuf:"fixed32,2,opt,name=multiplier,proto3" json:"multiplier,omitempty"`      // 收购倍数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FruitOdds) Reset() {
	*x = FruitOdds{}
	mi := &file_farming_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FruitOdds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FruitOdds) ProtoMessage() {}

func (x *FruitOdds) ProtoReflect() protoreflect.Message {
	mi := &file_farming_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FruitOdds.ProtoReflect.Descriptor instead.
func (*FruitOdds) Descriptor() ([]byte, []int) {
	return file_farming_type_proto_rawDescGZIP(), []int{0}
}

func (x *FruitOdds) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *FruitOdds) GetMultiplier() float32 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

// FieldState 单个田块的种植状态
type FieldState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldIndex    uint32                 `protobuf:"varint,1,opt,name=field_index,json=fieldIndex,proto3" json:"field_index,omitempty"` // 田块索引 (1-4)
	ItemId        uint32                 `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`             // 已种植水果ID (0为空闲)
	Count         uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`                             // 种植数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldState) Reset() {
	*x = FieldState{}
	mi := &file_farming_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldState) ProtoMessage() {}

func (x *FieldState) ProtoReflect() protoreflect.Message {
	mi := &file_farming_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldState.ProtoReflect.Descriptor instead.
func (*FieldState) Descriptor() ([]byte, []int) {
	return file_farming_type_proto_rawDescGZIP(), []int{1}
}

func (x *FieldState) GetFieldIndex() uint32 {
	if x != nil {
		return x.FieldIndex
	}
	return 0
}

func (x *FieldState) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *FieldState) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// FarmingInfo 种田实时业务状态
type FarmingInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*FieldState          `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"` // 当前玩家在该槽位的4块田详情
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`     // 所有者
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FarmingInfo) Reset() {
	*x = FarmingInfo{}
	mi := &file_farming_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FarmingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FarmingInfo) ProtoMessage() {}

func (x *FarmingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_farming_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FarmingInfo.ProtoReflect.Descriptor instead.
func (*FarmingInfo) Descriptor() ([]byte, []int) {
	return file_farming_type_proto_rawDescGZIP(), []int{2}
}

func (x *FarmingInfo) GetFields() []*FieldState {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *FarmingInfo) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// PlayerFarmingInfo 玩家种田信息
type PlayerFarmingInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *PlayerInfo            `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`   // 玩家信息
	Farming       *FarmingInfo           `protobuf:"bytes,2,opt,name=farming,proto3" json:"farming,omitempty"` // 种田状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerFarmingInfo) Reset() {
	*x = PlayerFarmingInfo{}
	mi := &file_farming_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerFarmingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerFarmingInfo) ProtoMessage() {}

func (x *PlayerFarmingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_farming_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerFarmingInfo.ProtoReflect.Descriptor instead.
func (*PlayerFarmingInfo) Descriptor() ([]byte, []int) {
	return file_farming_type_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerFarmingInfo) GetPlayer() *PlayerInfo {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *PlayerFarmingInfo) GetFarming() *FarmingInfo {
	if x != nil {
		return x.Farming
	}
	return nil
}

var File_farming_type_proto protoreflect.FileDescriptor

const file_farming_type_proto_rawDesc = "" +
	"\n" +
	"\x12farming_type.proto\x12\x04game\x1a\x11player_type.proto\"D\n" +
	"\tFruitOdds\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\rR\x06itemId\x12\x1e\n" +
	"\n" +
	"multiplier\x18\x02 \x01(\x02R\n" +
	"multiplier\"\\\n" +
	"\n" +
	"FieldState\x12\x1f\n" +
	"\vfield_index\x18\x01 \x01(\rR\n" +
	"fieldIndex\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\rR\x06itemId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\"K\n" +
	"\vFarmingInfo\x12(\n" +
	"\x06fields\x18\x01 \x03(\v2\x10.game.FieldStateR\x06fields\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\"j\n" +
	"\x11PlayerFarmingInfo\x12(\n" +
	"\x06player\x18\x01 \x01(\v2\x10.game.PlayerInfoR\x06player\x12+\n" +
	"\afarming\x18\x02 \x01(\v2\x11.game.FarmingInfoR\afarmingB1Z/github.com/lk2023060901/xiaojia-proto-game;gameb\x06proto3"

var (
	file_farming_type_proto_rawDescOnce sync.Once
	file_farming_type_proto_rawDescData []byte
)

func file_farming_type_proto_rawDescGZIP() []byte {
	file_farming_type_proto_rawDescOnce.Do(func() {
		file_farming_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_farming_type_proto_rawDesc), len(file_farming_type_proto_rawDesc)))
	})
	return file_farming_type_proto_rawDescData
}

var file_farming_type_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_farming_type_proto_goTypes = []any{
	(*FruitOdds)(nil),         // 0: game.FruitOdds
	(*FieldState)(nil),        // 1: game.FieldState
	(*FarmingInfo)(nil),       // 2: game.FarmingInfo
	(*PlayerFarmingInfo)(nil), // 3: game.PlayerFarmingInfo
	(*PlayerInfo)(nil),        // 4: game.PlayerInfo
}
var file_farming_type_proto_depIdxs = []int32{
	1, // 0: game.FarmingInfo.fields:type_name -> game.FieldState
	4, // 1: game.PlayerFarmingInfo.player:type_name -> game.PlayerInfo
	2, // 2: game.PlayerFarmingInfo.farming:type_name -> game.FarmingInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_farming_type_proto_init() }
func file_farming_type_proto_init() {
	if File_farming_type_proto != nil {
		return
	}
	file_player_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_farming_type_proto_rawDesc), len(file_farming_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_farming_type_proto_goTypes,
		DependencyIndexes: file_farming_type_proto_depIdxs,
		MessageInfos:      file_farming_type_proto_msgTypes,
	}.Build()
	File_farming_type_proto = out.File
	file_farming_type_proto_goTypes = nil
	file_farming_type_proto_depIdxs = nil
}
