// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/op_code.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OpCode 操作码定义
//
// 号段分配规则：
//   - 每个玩法保留 1000 个号段
//   - 0-999: 系统保留
type OpCode int32

const (
	// ============================================================
	// 系统保留 (0-999)
	// ============================================================
	OpCode_OP_NONE OpCode = 0
	// 客户端认证（Client -> Gateway）
	OpCode_OP_AUTH_REQ OpCode = 1
	OpCode_OP_AUTH_RSP OpCode = 2
)

// Enum value maps for OpCode.
var (
	OpCode_name = map[int32]string{
		0: "OP_NONE",
		1: "OP_AUTH_REQ",
		2: "OP_AUTH_RSP",
	}
	OpCode_value = map[string]int32{
		"OP_NONE":     0,
		"OP_AUTH_REQ": 1,
		"OP_AUTH_RSP": 2,
	}
)

func (x OpCode) Enum() *OpCode {
	p := new(OpCode)
	*p = x
	return p
}

func (x OpCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_op_code_proto_enumTypes[0].Descriptor()
}

func (OpCode) Type() protoreflect.EnumType {
	return &file_proto_op_code_proto_enumTypes[0]
}

func (x OpCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpCode.Descriptor instead.
func (OpCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_op_code_proto_rawDescGZIP(), []int{0}
}

var File_proto_op_code_proto protoreflect.FileDescriptor

const file_proto_op_code_proto_rawDesc = "" +
	"\n" +
	"\x13proto/op_code.proto\x12\x04game*7\n" +
	"\x06OpCode\x12\v\n" +
	"\aOP_NONE\x10\x00\x12\x0f\n" +
	"\vOP_AUTH_REQ\x10\x01\x12\x0f\n" +
	"\vOP_AUTH_RSP\x10\x02B1Z/github.com/lk2023060901/xiaojia-proto-game;gameb\x06proto3"

var (
	file_proto_op_code_proto_rawDescOnce sync.Once
	file_proto_op_code_proto_rawDescData []byte
)

func file_proto_op_code_proto_rawDescGZIP() []byte {
	file_proto_op_code_proto_rawDescOnce.Do(func() {
		file_proto_op_code_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_op_code_proto_rawDesc), len(file_proto_op_code_proto_rawDesc)))
	})
	return file_proto_op_code_proto_rawDescData
}

var file_proto_op_code_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_op_code_proto_goTypes = []any{
	(OpCode)(0), // 0: game.OpCode
}
var file_proto_op_code_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_op_code_proto_init() }
func file_proto_op_code_proto_init() {
	if File_proto_op_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_op_code_proto_rawDesc), len(file_proto_op_code_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_op_code_proto_goTypes,
		DependencyIndexes: file_proto_op_code_proto_depIdxs,
		EnumInfos:         file_proto_op_code_proto_enumTypes,
	}.Build()
	File_proto_op_code_proto = out.File
	file_proto_op_code_proto_goTypes = nil
	file_proto_op_code_proto_depIdxs = nil
}
