// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: player_type.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RoleType 角色身份
type RoleType int32

const (
	RoleType_ROLE_UNKNOWN RoleType = 0
	RoleType_STREAMER     RoleType = 1 // 主播
	RoleType_PLAYER       RoleType = 2 // 玩家
)

// Enum value maps for RoleType.
var (
	RoleType_name = map[int32]string{
		0: "ROLE_UNKNOWN",
		1: "STREAMER",
		2: "PLAYER",
	}
	RoleType_value = map[string]int32{
		"ROLE_UNKNOWN": 0,
		"STREAMER":     1,
		"PLAYER":       2,
	}
)

func (x RoleType) Enum() *RoleType {
	p := new(RoleType)
	*p = x
	return p
}

func (x RoleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoleType) Descriptor() protoreflect.EnumDescriptor {
	return file_player_type_proto_enumTypes[0].Descriptor()
}

func (RoleType) Type() protoreflect.EnumType {
	return &file_player_type_proto_enumTypes[0]
}

func (x RoleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoleType.Descriptor instead.
func (RoleType) EnumDescriptor() ([]byte, []int) {
	return file_player_type_proto_rawDescGZIP(), []int{0}
}

// PlayerInfo 玩家基础信息
type PlayerInfo struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Uid                  uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                                                                   // 玩家UID
	Nickname             string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`                                                          // 昵称
	AvatarUrl            string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`                                       // 头像地址
	AvatarFrame          uint32                 `protobuf:"varint,4,opt,name=avatar_frame,json=avatarFrame,proto3" json:"avatar_frame,omitempty"`                                // 头像框ID
	ChatBubble           uint32                 `protobuf:"varint,5,opt,name=chat_bubble,json=chatBubble,proto3" json:"chat_bubble,omitempty"`                                   // 气泡框ID
	VipLevel             uint32                 `protobuf:"varint,6,opt,name=vip_level,json=vipLevel,proto3" json:"vip_level,omitempty"`                                         // VIP等级
	VipExp               uint32                 `protobuf:"varint,7,opt,name=vip_exp,json=vipExp,proto3" json:"vip_exp,omitempty"`                                               // VIP经验值
	DecorEnergy          int64                  `protobuf:"varint,8,opt,name=decor_energy,json=decorEnergy,proto3" json:"decor_energy,omitempty"`                                // 装饰能量
	DailyVipEnergyGained int64                  `protobuf:"varint,9,opt,name=daily_vip_energy_gained,json=dailyVipEnergyGained,proto3" json:"daily_vip_energy_gained,omitempty"` // 今日已领取的VIP额外能量
	ModelId              uint32                 `protobuf:"varint,10,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`                                           // 角色模型ID
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	mi := &file_player_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_player_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_player_type_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerInfo) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PlayerInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *PlayerInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *PlayerInfo) GetAvatarFrame() uint32 {
	if x != nil {
		return x.AvatarFrame
	}
	return 0
}

func (x *PlayerInfo) GetChatBubble() uint32 {
	if x != nil {
		return x.ChatBubble
	}
	return 0
}

func (x *PlayerInfo) GetVipLevel() uint32 {
	if x != nil {
		return x.VipLevel
	}
	return 0
}

func (x *PlayerInfo) GetVipExp() uint32 {
	if x != nil {
		return x.VipExp
	}
	return 0
}

func (x *PlayerInfo) GetDecorEnergy() int64 {
	if x != nil {
		return x.DecorEnergy
	}
	return 0
}

func (x *PlayerInfo) GetDailyVipEnergyGained() int64 {
	if x != nil {
		return x.DailyVipEnergyGained
	}
	return 0
}

func (x *PlayerInfo) GetModelId() uint32 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

var File_player_type_proto protoreflect.FileDescriptor

const file_player_type_proto_rawDesc = "" +
	"\n" +
	"\x11player_type.proto\x12\x04game\"\xc8\x02\n" +
	"\n" +
	"PlayerInfo\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12!\n" +
	"\favatar_frame\x18\x04 \x01(\rR\vavatarFrame\x12\x1f\n" +
	"\vchat_bubble\x18\x05 \x01(\rR\n" +
	"chatBubble\x12\x1b\n" +
	"\tvip_level\x18\x06 \x01(\rR\bvipLevel\x12\x17\n" +
	"\avip_exp\x18\a \x01(\rR\x06vipExp\x12!\n" +
	"\fdecor_energy\x18\b \x01(\x03R\vdecorEnergy\x125\n" +
	"\x17daily_vip_energy_gained\x18\t \x01(\x03R\x14dailyVipEnergyGained\x12\x19\n" +
	"\bmodel_id\x18\n" +
	" \x01(\rR\amodelId*6\n" +
	"\bRoleType\x12\x10\n" +
	"\fROLE_UNKNOWN\x10\x00\x12\f\n" +
	"\bSTREAMER\x10\x01\x12\n" +
	"\n" +
	"\x06PLAYER\x10\x02B1Z/github.com/lk2023060901/xiaojia-proto-game;gameb\x06proto3"

var (
	file_player_type_proto_rawDescOnce sync.Once
	file_player_type_proto_rawDescData []byte
)

func file_player_type_proto_rawDescGZIP() []byte {
	file_player_type_proto_rawDescOnce.Do(func() {
		file_player_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_player_type_proto_rawDesc), len(file_player_type_proto_rawDesc)))
	})
	return file_player_type_proto_rawDescData
}

var file_player_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_player_type_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_player_type_proto_goTypes = []any{
	(RoleType)(0),      // 0: game.RoleType
	(*PlayerInfo)(nil), // 1: game.PlayerInfo
}
var file_player_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_player_type_proto_init() }
func file_player_type_proto_init() {
	if File_player_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_player_type_proto_rawDesc), len(file_player_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_player_type_proto_goTypes,
		DependencyIndexes: file_player_type_proto_depIdxs,
		EnumInfos:         file_player_type_proto_enumTypes,
		MessageInfos:      file_player_type_proto_msgTypes,
	}.Build()
	File_player_type_proto = out.File
	file_player_type_proto_goTypes = nil
	file_player_type_proto_depIdxs = nil
}
