// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: rank_type.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RankType 排行榜类型
type RankType int32

const (
	RankType_RANK_TYPE_NONE            RankType = 0
	RankType_RANK_FARMING_PROFIT_MAX   RankType = 1 // 种田历史最高收益排行榜
	RankType_RANK_ENERGY_CONSUME_TOTAL RankType = 2 // 装饰能量累积消耗排行榜
	RankType_RANK_COMPETITION_SCORE    RankType = 3 // 竞赛全服主播积分排行榜
	RankType_RANK_COMP_SIGNUP_CONTRIB  RankType = 4 // [单直播间] 竞赛报名阶段助力贡献排行榜
	RankType_RANK_COMP_PK_CONTRIB      RankType = 5 // [全服] 竞赛PK阶段玩家贡献排行榜
)

// Enum value maps for RankType.
var (
	RankType_name = map[int32]string{
		0: "RANK_TYPE_NONE",
		1: "RANK_FARMING_PROFIT_MAX",
		2: "RANK_ENERGY_CONSUME_TOTAL",
		3: "RANK_COMPETITION_SCORE",
		4: "RANK_COMP_SIGNUP_CONTRIB",
		5: "RANK_COMP_PK_CONTRIB",
	}
	RankType_value = map[string]int32{
		"RANK_TYPE_NONE":            0,
		"RANK_FARMING_PROFIT_MAX":   1,
		"RANK_ENERGY_CONSUME_TOTAL": 2,
		"RANK_COMPETITION_SCORE":    3,
		"RANK_COMP_SIGNUP_CONTRIB":  4,
		"RANK_COMP_PK_CONTRIB":      5,
	}
)

func (x RankType) Enum() *RankType {
	p := new(RankType)
	*p = x
	return p
}

func (x RankType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RankType) Descriptor() protoreflect.EnumDescriptor {
	return file_rank_type_proto_enumTypes[0].Descriptor()
}

func (RankType) Type() protoreflect.EnumType {
	return &file_rank_type_proto_enumTypes[0]
}

func (x RankType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RankType.Descriptor instead.
func (RankType) EnumDescriptor() ([]byte, []int) {
	return file_rank_type_proto_rawDescGZIP(), []int{0}
}

// RankItem 单个排名项信息
type RankItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          uint32                 `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`    // 排名 (1, 2, 3...)
	Player        *PlayerInfo            `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"` // 玩家基础信息 (含头像、昵称、VIP、模型ID等)
	Score         int64                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`  // 核心数值 (最高收益、累积消耗、助力贡献或PK积分)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankItem) Reset() {
	*x = RankItem{}
	mi := &file_rank_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankItem) ProtoMessage() {}

func (x *RankItem) ProtoReflect() protoreflect.Message {
	mi := &file_rank_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankItem.ProtoReflect.Descriptor instead.
func (*RankItem) Descriptor() ([]byte, []int) {
	return file_rank_type_proto_rawDescGZIP(), []int{0}
}

func (x *RankItem) GetRank() uint32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *RankItem) GetPlayer() *PlayerInfo {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *RankItem) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_rank_type_proto protoreflect.FileDescriptor

const file_rank_type_proto_rawDesc = "" +
	"\n" +
	"\x0frank_type.proto\x12\x04game\x1a\x11player_type.proto\"^\n" +
	"\bRankItem\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\rR\x04rank\x12(\n" +
	"\x06player\x18\x02 \x01(\v2\x10.game.PlayerInfoR\x06player\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x03R\x05score*\xae\x01\n" +
	"\bRankType\x12\x12\n" +
	"\x0eRANK_TYPE_NONE\x10\x00\x12\x1b\n" +
	"\x17RANK_FARMING_PROFIT_MAX\x10\x01\x12\x1d\n" +
	"\x19RANK_ENERGY_CONSUME_TOTAL\x10\x02\x12\x1a\n" +
	"\x16RANK_COMPETITION_SCORE\x10\x03\x12\x1c\n" +
	"\x18RANK_COMP_SIGNUP_CONTRIB\x10\x04\x12\x18\n" +
	"\x14RANK_COMP_PK_CONTRIB\x10\x05B1Z/github.com/lk2023060901/xiaojia-proto-game;gameb\x06proto3"

var (
	file_rank_type_proto_rawDescOnce sync.Once
	file_rank_type_proto_rawDescData []byte
)

func file_rank_type_proto_rawDescGZIP() []byte {
	file_rank_type_proto_rawDescOnce.Do(func() {
		file_rank_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rank_type_proto_rawDesc), len(file_rank_type_proto_rawDesc)))
	})
	return file_rank_type_proto_rawDescData
}

var file_rank_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rank_type_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rank_type_proto_goTypes = []any{
	(RankType)(0),      // 0: game.RankType
	(*RankItem)(nil),   // 1: game.RankItem
	(*PlayerInfo)(nil), // 2: game.PlayerInfo
}
var file_rank_type_proto_depIdxs = []int32{
	2, // 0: game.RankItem.player:type_name -> game.PlayerInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rank_type_proto_init() }
func file_rank_type_proto_init() {
	if File_rank_type_proto != nil {
		return
	}
	file_player_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rank_type_proto_rawDesc), len(file_rank_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rank_type_proto_goTypes,
		DependencyIndexes: file_rank_type_proto_depIdxs,
		EnumInfos:         file_rank_type_proto_enumTypes,
		MessageInfos:      file_rank_type_proto_msgTypes,
	}.Build()
	File_rank_type_proto = out.File
	file_rank_type_proto_goTypes = nil
	file_rank_type_proto_depIdxs = nil
}
