// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: rank.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetRankReq [C2S] 玩家请求获取特定类型的排行榜
type GetRankReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RankType      RankType               `protobuf:"varint,1,opt,name=rank_type,json=rankType,proto3,enum=game.RankType" json:"rank_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRankReq) Reset() {
	*x = GetRankReq{}
	mi := &file_rank_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRankReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRankReq) ProtoMessage() {}

func (x *GetRankReq) ProtoReflect() protoreflect.Message {
	mi := &file_rank_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankReq.ProtoReflect.Descriptor instead.
func (*GetRankReq) Descriptor() ([]byte, []int) {
	return file_rank_proto_rawDescGZIP(), []int{0}
}

func (x *GetRankReq) GetRankType() RankType {
	if x != nil {
		return x.RankType
	}
	return RankType_RANK_TYPE_NONE
}

// SyncRank [S2C] 服务端下发/同步排行榜数据
type SyncRank struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RankType      RankType               `protobuf:"varint,1,opt,name=rank_type,json=rankType,proto3,enum=game.RankType" json:"rank_type,omitempty"`
	Items         []*RankItem            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`                 // 榜单前 N 名列表
	MyRank        *RankItem              `protobuf:"bytes,3,opt,name=my_rank,json=myRank,proto3" json:"my_rank,omitempty"` // 玩家自己的当前排名信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRank) Reset() {
	*x = SyncRank{}
	mi := &file_rank_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRank) ProtoMessage() {}

func (x *SyncRank) ProtoReflect() protoreflect.Message {
	mi := &file_rank_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRank.ProtoReflect.Descriptor instead.
func (*SyncRank) Descriptor() ([]byte, []int) {
	return file_rank_proto_rawDescGZIP(), []int{1}
}

func (x *SyncRank) GetRankType() RankType {
	if x != nil {
		return x.RankType
	}
	return RankType_RANK_TYPE_NONE
}

func (x *SyncRank) GetItems() []*RankItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SyncRank) GetMyRank() *RankItem {
	if x != nil {
		return x.MyRank
	}
	return nil
}

var File_rank_proto protoreflect.FileDescriptor

const file_rank_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"rank.proto\x12\x04game\x1a\x0frank_type.proto\"9\n" +
	"\n" +
	"GetRankReq\x12+\n" +
	"\trank_type\x18\x01 \x01(\x0e2\x0e.game.RankTypeR\brankType\"\x86\x01\n" +
	"\bSyncRank\x12+\n" +
	"\trank_type\x18\x01 \x01(\x0e2\x0e.game.RankTypeR\brankType\x12$\n" +
	"\x05items\x18\x02 \x03(\v2\x0e.game.RankItemR\x05items\x12'\n" +
	"\amy_rank\x18\x03 \x01(\v2\x0e.game.RankItemR\x06myRankB1Z/github.com/lk2023060901/xiaojia-proto-game;gameb\x06proto3"

var (
	file_rank_proto_rawDescOnce sync.Once
	file_rank_proto_rawDescData []byte
)

func file_rank_proto_rawDescGZIP() []byte {
	file_rank_proto_rawDescOnce.Do(func() {
		file_rank_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rank_proto_rawDesc), len(file_rank_proto_rawDesc)))
	})
	return file_rank_proto_rawDescData
}

var file_rank_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rank_proto_goTypes = []any{
	(*GetRankReq)(nil), // 0: game.GetRankReq
	(*SyncRank)(nil),   // 1: game.SyncRank
	(RankType)(0),      // 2: game.RankType
	(*RankItem)(nil),   // 3: game.RankItem
}
var file_rank_proto_depIdxs = []int32{
	2, // 0: game.GetRankReq.rank_type:type_name -> game.RankType
	2, // 1: game.SyncRank.rank_type:type_name -> game.RankType
	3, // 2: game.SyncRank.items:type_name -> game.RankItem
	3, // 3: game.SyncRank.my_rank:type_name -> game.RankItem
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_rank_proto_init() }
func file_rank_proto_init() {
	if File_rank_proto != nil {
		return
	}
	file_rank_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rank_proto_rawDesc), len(file_rank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rank_proto_goTypes,
		DependencyIndexes: file_rank_proto_depIdxs,
		MessageInfos:      file_rank_proto_msgTypes,
	}.Build()
	File_rank_proto = out.File
	file_rank_proto_goTypes = nil
	file_rank_proto_depIdxs = nil
}
