// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: relationship_type.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RelationshipType 关系类型
type RelationshipType int32

const (
	RelationshipType_RELATION_NONE   RelationshipType = 0
	RelationshipType_RELATION_FRIEND RelationshipType = 1 // 好友
	RelationshipType_RELATION_BESTIE RelationshipType = 2 // 闺蜜
	RelationshipType_RELATION_LOVER  RelationshipType = 3 // 恋人
)

// Enum value maps for RelationshipType.
var (
	RelationshipType_name = map[int32]string{
		0: "RELATION_NONE",
		1: "RELATION_FRIEND",
		2: "RELATION_BESTIE",
		3: "RELATION_LOVER",
	}
	RelationshipType_value = map[string]int32{
		"RELATION_NONE":   0,
		"RELATION_FRIEND": 1,
		"RELATION_BESTIE": 2,
		"RELATION_LOVER":  3,
	}
)

func (x RelationshipType) Enum() *RelationshipType {
	p := new(RelationshipType)
	*p = x
	return p
}

func (x RelationshipType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelationshipType) Descriptor() protoreflect.EnumDescriptor {
	return file_relationship_type_proto_enumTypes[0].Descriptor()
}

func (RelationshipType) Type() protoreflect.EnumType {
	return &file_relationship_type_proto_enumTypes[0]
}

func (x RelationshipType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelationshipType.Descriptor instead.
func (RelationshipType) EnumDescriptor() ([]byte, []int) {
	return file_relationship_type_proto_rawDescGZIP(), []int{0}
}

// PlayerRelationship 玩家本人的详细关系项
type PlayerRelationship struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Type             RelationshipType       `protobuf:"varint,1,opt,name=type,proto3,enum=game.RelationshipType" json:"type,omitempty"`                        // 关系类型
	Level            uint32                 `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`                                                 // 关系等级
	Exp              uint32                 `protobuf:"varint,3,opt,name=exp,proto3" json:"exp,omitempty"`                                                     // 当前关系经验值
	DailyFlowersSent uint32                 `protobuf:"varint,4,opt,name=daily_flowers_sent,json=dailyFlowersSent,proto3" json:"daily_flowers_sent,omitempty"` // 今日双方互送鲜花的总数
	Uid              uint64                 `protobuf:"varint,5,opt,name=uid,proto3" json:"uid,omitempty"`                                                     // 对方玩家的UID
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PlayerRelationship) Reset() {
	*x = PlayerRelationship{}
	mi := &file_relationship_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerRelationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRelationship) ProtoMessage() {}

func (x *PlayerRelationship) ProtoReflect() protoreflect.Message {
	mi := &file_relationship_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRelationship.ProtoReflect.Descriptor instead.
func (*PlayerRelationship) Descriptor() ([]byte, []int) {
	return file_relationship_type_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerRelationship) GetType() RelationshipType {
	if x != nil {
		return x.Type
	}
	return RelationshipType_RELATION_NONE
}

func (x *PlayerRelationship) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PlayerRelationship) GetExp() uint32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *PlayerRelationship) GetDailyFlowersSent() uint32 {
	if x != nil {
		return x.DailyFlowersSent
	}
	return 0
}

func (x *PlayerRelationship) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

var File_relationship_type_proto protoreflect.FileDescriptor

const file_relationship_type_proto_rawDesc = "" +
	"\n" +
	"\x17relationship_type.proto\x12\x04game\"\xa8\x01\n" +
	"\x12PlayerRelationship\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.game.RelationshipTypeR\x04type\x12\x14\n" +
	"\x05level\x18\x02 \x01(\rR\x05level\x12\x10\n" +
	"\x03exp\x18\x03 \x01(\rR\x03exp\x12,\n" +
	"\x12daily_flowers_sent\x18\x04 \x01(\rR\x10dailyFlowersSent\x12\x10\n" +
	"\x03uid\x18\x05 \x01(\x04R\x03uid*c\n" +
	"\x10RelationshipType\x12\x11\n" +
	"\rRELATION_NONE\x10\x00\x12\x13\n" +
	"\x0fRELATION_FRIEND\x10\x01\x12\x13\n" +
	"\x0fRELATION_BESTIE\x10\x02\x12\x12\n" +
	"\x0eRELATION_LOVER\x10\x03B1Z/github.com/lk2023060901/xiaojia-proto-game;gameb\x06proto3"

var (
	file_relationship_type_proto_rawDescOnce sync.Once
	file_relationship_type_proto_rawDescData []byte
)

func file_relationship_type_proto_rawDescGZIP() []byte {
	file_relationship_type_proto_rawDescOnce.Do(func() {
		file_relationship_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relationship_type_proto_rawDesc), len(file_relationship_type_proto_rawDesc)))
	})
	return file_relationship_type_proto_rawDescData
}

var file_relationship_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_relationship_type_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_relationship_type_proto_goTypes = []any{
	(RelationshipType)(0),      // 0: game.RelationshipType
	(*PlayerRelationship)(nil), // 1: game.PlayerRelationship
}
var file_relationship_type_proto_depIdxs = []int32{
	0, // 0: game.PlayerRelationship.type:type_name -> game.RelationshipType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_relationship_type_proto_init() }
func file_relationship_type_proto_init() {
	if File_relationship_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relationship_type_proto_rawDesc), len(file_relationship_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relationship_type_proto_goTypes,
		DependencyIndexes: file_relationship_type_proto_depIdxs,
		EnumInfos:         file_relationship_type_proto_enumTypes,
		MessageInfos:      file_relationship_type_proto_msgTypes,
	}.Build()
	File_relationship_type_proto = out.File
	file_relationship_type_proto_goTypes = nil
	file_relationship_type_proto_depIdxs = nil
}
