// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: relationship.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SyncPlayerRelationships [S2C] 全量同步给玩家本人的关系列表
type SyncPlayerRelationships struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relationships []*PlayerRelationship  `protobuf:"bytes,1,rep,name=relationships,proto3" json:"relationships,omitempty"`
	SlotId        uint32                 `protobuf:"varint,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	Uuid          string                 `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncPlayerRelationships) Reset() {
	*x = SyncPlayerRelationships{}
	mi := &file_relationship_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncPlayerRelationships) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPlayerRelationships) ProtoMessage() {}

func (x *SyncPlayerRelationships) ProtoReflect() protoreflect.Message {
	mi := &file_relationship_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPlayerRelationships.ProtoReflect.Descriptor instead.
func (*SyncPlayerRelationships) Descriptor() ([]byte, []int) {
	return file_relationship_proto_rawDescGZIP(), []int{0}
}

func (x *SyncPlayerRelationships) GetRelationships() []*PlayerRelationship {
	if x != nil {
		return x.Relationships
	}
	return nil
}

func (x *SyncPlayerRelationships) GetSlotId() uint32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *SyncPlayerRelationships) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// SyncRelationshipUpdate [S2C] 增量同步单项数值变动
type SyncRelationshipUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartnerUuid   string                 `protobuf:"bytes,1,opt,name=partner_uuid,json=partnerUuid,proto3" json:"partner_uuid,omitempty"`     // 对方UUID
	NewExp        uint32                 `protobuf:"varint,2,opt,name=new_exp,json=newExp,proto3" json:"new_exp,omitempty"`                   // 最新经验值
	DailyFlowers  uint32                 `protobuf:"varint,3,opt,name=daily_flowers,json=dailyFlowers,proto3" json:"daily_flowers,omitempty"` // 最新每日鲜花数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRelationshipUpdate) Reset() {
	*x = SyncRelationshipUpdate{}
	mi := &file_relationship_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRelationshipUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRelationshipUpdate) ProtoMessage() {}

func (x *SyncRelationshipUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_relationship_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRelationshipUpdate.ProtoReflect.Descriptor instead.
func (*SyncRelationshipUpdate) Descriptor() ([]byte, []int) {
	return file_relationship_proto_rawDescGZIP(), []int{1}
}

func (x *SyncRelationshipUpdate) GetPartnerUuid() string {
	if x != nil {
		return x.PartnerUuid
	}
	return ""
}

func (x *SyncRelationshipUpdate) GetNewExp() uint32 {
	if x != nil {
		return x.NewExp
	}
	return 0
}

func (x *SyncRelationshipUpdate) GetDailyFlowers() uint32 {
	if x != nil {
		return x.DailyFlowers
	}
	return 0
}

// SyncSlotRelationship [S2C] 广播给直播间所有人：同步特定槽位上玩家间的关系标志
type SyncSlotRelationship struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        uint32                 `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`          // 槽位ID
	Type          RelationshipType       `protobuf:"varint,2,opt,name=type,proto3,enum=game.RelationshipType" json:"type,omitempty"` // 关系类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncSlotRelationship) Reset() {
	*x = SyncSlotRelationship{}
	mi := &file_relationship_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncSlotRelationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSlotRelationship) ProtoMessage() {}

func (x *SyncSlotRelationship) ProtoReflect() protoreflect.Message {
	mi := &file_relationship_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSlotRelationship.ProtoReflect.Descriptor instead.
func (*SyncSlotRelationship) Descriptor() ([]byte, []int) {
	return file_relationship_proto_rawDescGZIP(), []int{2}
}

func (x *SyncSlotRelationship) GetSlotId() uint32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *SyncSlotRelationship) GetType() RelationshipType {
	if x != nil {
		return x.Type
	}
	return RelationshipType_RELATION_NONE
}

var File_relationship_proto protoreflect.FileDescriptor

const file_relationship_proto_rawDesc = "" +
	"\n" +
	"\x12relationship.proto\x12\x04game\x1a\x17relationship_type.proto\"\x86\x01\n" +
	"\x17SyncPlayerRelationships\x12>\n" +
	"\rrelationships\x18\x01 \x03(\v2\x18.game.PlayerRelationshipR\rrelationships\x12\x17\n" +
	"\aslot_id\x18\x02 \x01(\rR\x06slotId\x12\x12\n" +
	"\x04uuid\x18\x03 \x01(\tR\x04uuid\"y\n" +
	"\x16SyncRelationshipUpdate\x12!\n" +
	"\fpartner_uuid\x18\x01 \x01(\tR\vpartnerUuid\x12\x17\n" +
	"\anew_exp\x18\x02 \x01(\rR\x06newExp\x12#\n" +
	"\rdaily_flowers\x18\x03 \x01(\rR\fdailyFlowers\"[\n" +
	"\x14SyncSlotRelationship\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\rR\x06slotId\x12*\n" +
	"\x04type\x18\x02 \x01(\x0e2\x16.game.RelationshipTypeR\x04typeB1Z/github.com/lk2023060901/xiaojia-proto-game;gameb\x06proto3"

var (
	file_relationship_proto_rawDescOnce sync.Once
	file_relationship_proto_rawDescData []byte
)

func file_relationship_proto_rawDescGZIP() []byte {
	file_relationship_proto_rawDescOnce.Do(func() {
		file_relationship_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relationship_proto_rawDesc), len(file_relationship_proto_rawDesc)))
	})
	return file_relationship_proto_rawDescData
}

var file_relationship_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_relationship_proto_goTypes = []any{
	(*SyncPlayerRelationships)(nil), // 0: game.SyncPlayerRelationships
	(*SyncRelationshipUpdate)(nil),  // 1: game.SyncRelationshipUpdate
	(*SyncSlotRelationship)(nil),    // 2: game.SyncSlotRelationship
	(*PlayerRelationship)(nil),      // 3: game.PlayerRelationship
	(RelationshipType)(0),           // 4: game.RelationshipType
}
var file_relationship_proto_depIdxs = []int32{
	3, // 0: game.SyncPlayerRelationships.relationships:type_name -> game.PlayerRelationship
	4, // 1: game.SyncSlotRelationship.type:type_name -> game.RelationshipType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_relationship_proto_init() }
func file_relationship_proto_init() {
	if File_relationship_proto != nil {
		return
	}
	file_relationship_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relationship_proto_rawDesc), len(file_relationship_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relationship_proto_goTypes,
		DependencyIndexes: file_relationship_proto_depIdxs,
		MessageInfos:      file_relationship_proto_msgTypes,
	}.Build()
	File_relationship_proto = out.File
	file_relationship_proto_goTypes = nil
	file_relationship_proto_depIdxs = nil
}
