// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: slot.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// [S2C] 全量同步当前主播的所有槽位信息
type SyncAnchorSlots struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slots         []*SlotInfo            `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty"` // 9个槽位的数据列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncAnchorSlots) Reset() {
	*x = SyncAnchorSlots{}
	mi := &file_slot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAnchorSlots) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAnchorSlots) ProtoMessage() {}

func (x *SyncAnchorSlots) ProtoReflect() protoreflect.Message {
	mi := &file_slot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAnchorSlots.ProtoReflect.Descriptor instead.
func (*SyncAnchorSlots) Descriptor() ([]byte, []int) {
	return file_slot_proto_rawDescGZIP(), []int{0}
}

func (x *SyncAnchorSlots) GetSlots() []*SlotInfo {
	if x != nil {
		return x.Slots
	}
	return nil
}

// [S2C] 增量同步单个槽位的状态变化
// 用于：切换模式、PK分数跳动、灵气消耗、所有者迁移等
type SyncAnchorSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          *SlotInfo              `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"` // 变更后的槽位数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncAnchorSlot) Reset() {
	*x = SyncAnchorSlot{}
	mi := &file_slot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAnchorSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAnchorSlot) ProtoMessage() {}

func (x *SyncAnchorSlot) ProtoReflect() protoreflect.Message {
	mi := &file_slot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAnchorSlot.ProtoReflect.Descriptor instead.
func (*SyncAnchorSlot) Descriptor() ([]byte, []int) {
	return file_slot_proto_rawDescGZIP(), []int{1}
}

func (x *SyncAnchorSlot) GetSlot() *SlotInfo {
	if x != nil {
		return x.Slot
	}
	return nil
}

// SyncSlotModel [S2C] 同步特定槽位上的玩家模型变化
type SyncSlotModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        uint32                 `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`    // 槽位编号
	Uid           uint64                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`                        // 玩家UID
	ModelId       uint32                 `protobuf:"varint,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"` // 最新模型ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncSlotModel) Reset() {
	*x = SyncSlotModel{}
	mi := &file_slot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncSlotModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSlotModel) ProtoMessage() {}

func (x *SyncSlotModel) ProtoReflect() protoreflect.Message {
	mi := &file_slot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSlotModel.ProtoReflect.Descriptor instead.
func (*SyncSlotModel) Descriptor() ([]byte, []int) {
	return file_slot_proto_rawDescGZIP(), []int{2}
}

func (x *SyncSlotModel) GetSlotId() uint32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *SyncSlotModel) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SyncSlotModel) GetModelId() uint32 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

// SyncSlotAddPlayer [S2C] 同步槽位新增人员
type SyncSlotAddPlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        uint32                 `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`    // 槽位编号
	Info          *PlayerFarmingInfo     `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`                       // 玩家详情及种田状态
	IsOwner       bool                   `protobuf:"varint,3,opt,name=is_owner,json=isOwner,proto3" json:"is_owner,omitempty"` // 是否作为所有者加入
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncSlotAddPlayer) Reset() {
	*x = SyncSlotAddPlayer{}
	mi := &file_slot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncSlotAddPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSlotAddPlayer) ProtoMessage() {}

func (x *SyncSlotAddPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_slot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSlotAddPlayer.ProtoReflect.Descriptor instead.
func (*SyncSlotAddPlayer) Descriptor() ([]byte, []int) {
	return file_slot_proto_rawDescGZIP(), []int{3}
}

func (x *SyncSlotAddPlayer) GetSlotId() uint32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *SyncSlotAddPlayer) GetInfo() *PlayerFarmingInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *SyncSlotAddPlayer) GetIsOwner() bool {
	if x != nil {
		return x.IsOwner
	}
	return false
}

// SyncSlotRemovePlayer [S2C] 同步槽位人员离开
type SyncSlotRemovePlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        uint32                 `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"` // 槽位编号
	Uid           uint64                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`                     // 离开玩家的UID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncSlotRemovePlayer) Reset() {
	*x = SyncSlotRemovePlayer{}
	mi := &file_slot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncSlotRemovePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSlotRemovePlayer) ProtoMessage() {}

func (x *SyncSlotRemovePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_slot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSlotRemovePlayer.ProtoReflect.Descriptor instead.
func (*SyncSlotRemovePlayer) Descriptor() ([]byte, []int) {
	return file_slot_proto_rawDescGZIP(), []int{4}
}

func (x *SyncSlotRemovePlayer) GetSlotId() uint32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *SyncSlotRemovePlayer) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

var File_slot_proto protoreflect.FileDescriptor

const file_slot_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"slot.proto\x12\x04game\x1a\x0fslot_type.proto\x1a\x12farming_type.proto\"7\n" +
	"\x0fSyncAnchorSlots\x12$\n" +
	"\x05slots\x18\x01 \x03(\v2\x0e.game.SlotInfoR\x05slots\"4\n" +
	"\x0eSyncAnchorSlot\x12\"\n" +
	"\x04slot\x18\x01 \x01(\v2\x0e.game.SlotInfoR\x04slot\"U\n" +
	"\rSyncSlotModel\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\rR\x06slotId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x04R\x03uid\x12\x19\n" +
	"\bmodel_id\x18\x03 \x01(\rR\amodelId\"t\n" +
	"\x11SyncSlotAddPlayer\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\rR\x06slotId\x12+\n" +
	"\x04info\x18\x02 \x01(\v2\x17.game.PlayerFarmingInfoR\x04info\x12\x19\n" +
	"\bis_owner\x18\x03 \x01(\bR\aisOwner\"A\n" +
	"\x14SyncSlotRemovePlayer\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\rR\x06slotId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x04R\x03uidB1Z/github.com/lk2023060901/xiaojia-proto-game;gameb\x06proto3"

var (
	file_slot_proto_rawDescOnce sync.Once
	file_slot_proto_rawDescData []byte
)

func file_slot_proto_rawDescGZIP() []byte {
	file_slot_proto_rawDescOnce.Do(func() {
		file_slot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_slot_proto_rawDesc), len(file_slot_proto_rawDesc)))
	})
	return file_slot_proto_rawDescData
}

var file_slot_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_slot_proto_goTypes = []any{
	(*SyncAnchorSlots)(nil),      // 0: game.SyncAnchorSlots
	(*SyncAnchorSlot)(nil),       // 1: game.SyncAnchorSlot
	(*SyncSlotModel)(nil),        // 2: game.SyncSlotModel
	(*SyncSlotAddPlayer)(nil),    // 3: game.SyncSlotAddPlayer
	(*SyncSlotRemovePlayer)(nil), // 4: game.SyncSlotRemovePlayer
	(*SlotInfo)(nil),             // 5: game.SlotInfo
	(*PlayerFarmingInfo)(nil),    // 6: game.PlayerFarmingInfo
}
var file_slot_proto_depIdxs = []int32{
	5, // 0: game.SyncAnchorSlots.slots:type_name -> game.SlotInfo
	5, // 1: game.SyncAnchorSlot.slot:type_name -> game.SlotInfo
	6, // 2: game.SyncSlotAddPlayer.info:type_name -> game.PlayerFarmingInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_slot_proto_init() }
func file_slot_proto_init() {
	if File_slot_proto != nil {
		return
	}
	file_slot_type_proto_init()
	file_farming_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_slot_proto_rawDesc), len(file_slot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_slot_proto_goTypes,
		DependencyIndexes: file_slot_proto_depIdxs,
		MessageInfos:      file_slot_proto_msgTypes,
	}.Build()
	File_slot_proto = out.File
	file_slot_proto_goTypes = nil
	file_slot_proto_depIdxs = nil
}
