// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: slot_type.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SlotMode 槽位显示模式
type SlotMode int32

const (
	SlotMode_SLOT_MODE_BED     SlotMode = 0 // 床位模式
	SlotMode_SLOT_MODE_FARMING SlotMode = 1 // 种田模式
)

// Enum value maps for SlotMode.
var (
	SlotMode_name = map[int32]string{
		0: "SLOT_MODE_BED",
		1: "SLOT_MODE_FARMING",
	}
	SlotMode_value = map[string]int32{
		"SLOT_MODE_BED":     0,
		"SLOT_MODE_FARMING": 1,
	}
)

func (x SlotMode) Enum() *SlotMode {
	p := new(SlotMode)
	*p = x
	return p
}

func (x SlotMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SlotMode) Descriptor() protoreflect.EnumDescriptor {
	return file_slot_type_proto_enumTypes[0].Descriptor()
}

func (SlotMode) Type() protoreflect.EnumType {
	return &file_slot_type_proto_enumTypes[0]
}

func (x SlotMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SlotMode.Descriptor instead.
func (SlotMode) EnumDescriptor() ([]byte, []int) {
	return file_slot_type_proto_rawDescGZIP(), []int{0}
}

// SlotInfo 槽位完整信息包装器
type SlotInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        uint32                 `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`               // 槽位编号 (1-9)
	Owner         *PlayerInfo            `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`                                // 槽位所有者信息
	Partners      []*PlayerInfo          `protobuf:"bytes,3,rep,name=partners,proto3" json:"partners,omitempty"`                          // 共同拥有者列表 (床位共享/种田同步)
	Mode          SlotMode               `protobuf:"varint,4,opt,name=mode,proto3,enum=game.SlotMode" json:"mode,omitempty"`              // 当前显示的模式
	BedInfo       *BedInfo               `protobuf:"bytes,5,opt,name=bed_info,json=bedInfo,proto3" json:"bed_info,omitempty"`             // 床位详细数据 (仅mode=BED有效)
	FarmingInfo   *FarmingInfo           `protobuf:"bytes,6,opt,name=farming_info,json=farmingInfo,proto3" json:"farming_info,omitempty"` // 种田详细数据 (仅mode=FARMING有效)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotInfo) Reset() {
	*x = SlotInfo{}
	mi := &file_slot_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotInfo) ProtoMessage() {}

func (x *SlotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_slot_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotInfo.ProtoReflect.Descriptor instead.
func (*SlotInfo) Descriptor() ([]byte, []int) {
	return file_slot_type_proto_rawDescGZIP(), []int{0}
}

func (x *SlotInfo) GetSlotId() uint32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *SlotInfo) GetOwner() *PlayerInfo {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *SlotInfo) GetPartners() []*PlayerInfo {
	if x != nil {
		return x.Partners
	}
	return nil
}

func (x *SlotInfo) GetMode() SlotMode {
	if x != nil {
		return x.Mode
	}
	return SlotMode_SLOT_MODE_BED
}

func (x *SlotInfo) GetBedInfo() *BedInfo {
	if x != nil {
		return x.BedInfo
	}
	return nil
}

func (x *SlotInfo) GetFarmingInfo() *FarmingInfo {
	if x != nil {
		return x.FarmingInfo
	}
	return nil
}

var File_slot_type_proto protoreflect.FileDescriptor

const file_slot_type_proto_rawDesc = "" +
	"\n" +
	"\x0fslot_type.proto\x12\x04game\x1a\x11player_type.proto\x1a\x0ebed_type.proto\x1a\x12farming_type.proto\"\xfd\x01\n" +
	"\bSlotInfo\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\rR\x06slotId\x12&\n" +
	"\x05owner\x18\x02 \x01(\v2\x10.game.PlayerInfoR\x05owner\x12,\n" +
	"\bpartners\x18\x03 \x03(\v2\x10.game.PlayerInfoR\bpartners\x12\"\n" +
	"\x04mode\x18\x04 \x01(\x0e2\x0e.game.SlotModeR\x04mode\x12(\n" +
	"\bbed_info\x18\x05 \x01(\v2\r.game.BedInfoR\abedInfo\x124\n" +
	"\ffarming_info\x18\x06 \x01(\v2\x11.game.FarmingInfoR\vfarmingInfo*4\n" +
	"\bSlotMode\x12\x11\n" +
	"\rSLOT_MODE_BED\x10\x00\x12\x15\n" +
	"\x11SLOT_MODE_FARMING\x10\x01B1Z/github.com/lk2023060901/xiaojia-proto-game;gameb\x06proto3"

var (
	file_slot_type_proto_rawDescOnce sync.Once
	file_slot_type_proto_rawDescData []byte
)

func file_slot_type_proto_rawDescGZIP() []byte {
	file_slot_type_proto_rawDescOnce.Do(func() {
		file_slot_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_slot_type_proto_rawDesc), len(file_slot_type_proto_rawDesc)))
	})
	return file_slot_type_proto_rawDescData
}

var file_slot_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_slot_type_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_slot_type_proto_goTypes = []any{
	(SlotMode)(0),       // 0: game.SlotMode
	(*SlotInfo)(nil),    // 1: game.SlotInfo
	(*PlayerInfo)(nil),  // 2: game.PlayerInfo
	(*BedInfo)(nil),     // 3: game.BedInfo
	(*FarmingInfo)(nil), // 4: game.FarmingInfo
}
var file_slot_type_proto_depIdxs = []int32{
	2, // 0: game.SlotInfo.owner:type_name -> game.PlayerInfo
	2, // 1: game.SlotInfo.partners:type_name -> game.PlayerInfo
	0, // 2: game.SlotInfo.mode:type_name -> game.SlotMode
	3, // 3: game.SlotInfo.bed_info:type_name -> game.BedInfo
	4, // 4: game.SlotInfo.farming_info:type_name -> game.FarmingInfo
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_slot_type_proto_init() }
func file_slot_type_proto_init() {
	if File_slot_type_proto != nil {
		return
	}
	file_player_type_proto_init()
	file_bed_type_proto_init()
	file_farming_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_slot_type_proto_rawDesc), len(file_slot_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_slot_type_proto_goTypes,
		DependencyIndexes: file_slot_type_proto_depIdxs,
		EnumInfos:         file_slot_type_proto_enumTypes,
		MessageInfos:      file_slot_type_proto_msgTypes,
	}.Build()
	File_slot_type_proto = out.File
	file_slot_type_proto_goTypes = nil
	file_slot_type_proto_depIdxs = nil
}
