// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: store.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SyncStoreGoods [S2C] 下发/同步指定商店的所有商品列表
type SyncStoreGoods struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       uint32                 `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"` // 商店ID (对应 Store.xlsx)
	Items         []*StoreGoodsItem      `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`                     // 商品列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncStoreGoods) Reset() {
	*x = SyncStoreGoods{}
	mi := &file_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStoreGoods) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStoreGoods) ProtoMessage() {}

func (x *SyncStoreGoods) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStoreGoods.ProtoReflect.Descriptor instead.
func (*SyncStoreGoods) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{0}
}

func (x *SyncStoreGoods) GetStoreId() uint32 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *SyncStoreGoods) GetItems() []*StoreGoodsItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// SyncStoreGoodsItem [S2C] 同步单个商品的状态变更
type SyncStoreGoodsItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       uint32                 `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`       // 商店ID
	GoodsId       uint32                 `protobuf:"varint,2,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`       // 商品流水ID
	LimitLeft     uint32                 `protobuf:"varint,3,opt,name=limit_left,json=limitLeft,proto3" json:"limit_left,omitempty"` // 变更后最新的剩余限购数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncStoreGoodsItem) Reset() {
	*x = SyncStoreGoodsItem{}
	mi := &file_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStoreGoodsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStoreGoodsItem) ProtoMessage() {}

func (x *SyncStoreGoodsItem) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStoreGoodsItem.ProtoReflect.Descriptor instead.
func (*SyncStoreGoodsItem) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{1}
}

func (x *SyncStoreGoodsItem) GetStoreId() uint32 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *SyncStoreGoodsItem) GetGoodsId() uint32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *SyncStoreGoodsItem) GetLimitLeft() uint32 {
	if x != nil {
		return x.LimitLeft
	}
	return 0
}

// BuyStoreGoodsReq [C2S] 玩家购买商店道具请求
type BuyStoreGoodsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreType     StoreType              `protobuf:"varint,1,opt,name=store_type,json=storeType,proto3,enum=game.StoreType" json:"store_type,omitempty"` // 商店类型
	GoodsId       uint32                 `protobuf:"varint,2,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`                           // 商品流水ID
	Count         uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`                                              // 购买数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyStoreGoodsReq) Reset() {
	*x = BuyStoreGoodsReq{}
	mi := &file_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyStoreGoodsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyStoreGoodsReq) ProtoMessage() {}

func (x *BuyStoreGoodsReq) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyStoreGoodsReq.ProtoReflect.Descriptor instead.
func (*BuyStoreGoodsReq) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{2}
}

func (x *BuyStoreGoodsReq) GetStoreType() StoreType {
	if x != nil {
		return x.StoreType
	}
	return StoreType_STORE_TYPE_NONE
}

func (x *BuyStoreGoodsReq) GetGoodsId() uint32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *BuyStoreGoodsReq) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// BuyStoreGoodsRes [S2C] 玩家购买商店道具响应
type BuyStoreGoodsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrCode                `protobuf:"varint,1,opt,name=code,proto3,enum=game.ErrCode" json:"code,omitempty"`                              // 错误码
	StoreType     StoreType              `protobuf:"varint,2,opt,name=store_type,json=storeType,proto3,enum=game.StoreType" json:"store_type,omitempty"` // 商店类型
	GoodsId       uint32                 `protobuf:"varint,3,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`                           // 商品流水ID
	Count         uint32                 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`                                              // 购买数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyStoreGoodsRes) Reset() {
	*x = BuyStoreGoodsRes{}
	mi := &file_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyStoreGoodsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyStoreGoodsRes) ProtoMessage() {}

func (x *BuyStoreGoodsRes) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyStoreGoodsRes.ProtoReflect.Descriptor instead.
func (*BuyStoreGoodsRes) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{3}
}

func (x *BuyStoreGoodsRes) GetCode() ErrCode {
	if x != nil {
		return x.Code
	}
	return ErrCode_ERR_SUCCESS
}

func (x *BuyStoreGoodsRes) GetStoreType() StoreType {
	if x != nil {
		return x.StoreType
	}
	return StoreType_STORE_TYPE_NONE
}

func (x *BuyStoreGoodsRes) GetGoodsId() uint32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *BuyStoreGoodsRes) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_store_proto protoreflect.FileDescriptor

const file_store_proto_rawDesc = "" +
	"\n" +
	"\vstore.proto\x12\x04game\x1a\x10store_type.proto\x1a\x0eerr_code.proto\"W\n" +
	"\x0eSyncStoreGoods\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\rR\astoreId\x12*\n" +
	"\x05items\x18\x02 \x03(\v2\x14.game.StoreGoodsItemR\x05items\"i\n" +
	"\x12SyncStoreGoodsItem\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\rR\astoreId\x12\x19\n" +
	"\bgoods_id\x18\x02 \x01(\rR\agoodsId\x12\x1d\n" +
	"\n" +
	"limit_left\x18\x03 \x01(\rR\tlimitLeft\"s\n" +
	"\x10BuyStoreGoodsReq\x12.\n" +
	"\n" +
	"store_type\x18\x01 \x01(\x0e2\x0f.game.StoreTypeR\tstoreType\x12\x19\n" +
	"\bgoods_id\x18\x02 \x01(\rR\agoodsId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\"\x96\x01\n" +
	"\x10BuyStoreGoodsRes\x12!\n" +
	"\x04code\x18\x01 \x01(\x0e2\r.game.ErrCodeR\x04code\x12.\n" +
	"\n" +
	"store_type\x18\x02 \x01(\x0e2\x0f.game.StoreTypeR\tstoreType\x12\x19\n" +
	"\bgoods_id\x18\x03 \x01(\rR\agoodsId\x12\x14\n" +
	"\x05count\x18\x04 \x01(\rR\x05countB1Z/github.com/lk2023060901/xiaojia-proto-game;gameb\x06proto3"

var (
	file_store_proto_rawDescOnce sync.Once
	file_store_proto_rawDescData []byte
)

func file_store_proto_rawDescGZIP() []byte {
	file_store_proto_rawDescOnce.Do(func() {
		file_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_store_proto_rawDesc), len(file_store_proto_rawDesc)))
	})
	return file_store_proto_rawDescData
}

var file_store_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_store_proto_goTypes = []any{
	(*SyncStoreGoods)(nil),     // 0: game.SyncStoreGoods
	(*SyncStoreGoodsItem)(nil), // 1: game.SyncStoreGoodsItem
	(*BuyStoreGoodsReq)(nil),   // 2: game.BuyStoreGoodsReq
	(*BuyStoreGoodsRes)(nil),   // 3: game.BuyStoreGoodsRes
	(*StoreGoodsItem)(nil),     // 4: game.StoreGoodsItem
	(StoreType)(0),             // 5: game.StoreType
	(ErrCode)(0),               // 6: game.ErrCode
}
var file_store_proto_depIdxs = []int32{
	4, // 0: game.SyncStoreGoods.items:type_name -> game.StoreGoodsItem
	5, // 1: game.BuyStoreGoodsReq.store_type:type_name -> game.StoreType
	6, // 2: game.BuyStoreGoodsRes.code:type_name -> game.ErrCode
	5, // 3: game.BuyStoreGoodsRes.store_type:type_name -> game.StoreType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_store_proto_init() }
func file_store_proto_init() {
	if File_store_proto != nil {
		return
	}
	file_store_type_proto_init()
	file_err_code_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_store_proto_rawDesc), len(file_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_store_proto_goTypes,
		DependencyIndexes: file_store_proto_depIdxs,
		MessageInfos:      file_store_proto_msgTypes,
	}.Build()
	File_store_proto = out.File
	file_store_proto_goTypes = nil
	file_store_proto_depIdxs = nil
}
