// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: store_type.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StoreType 商店类型
type StoreType int32

const (
	StoreType_STORE_TYPE_NONE     StoreType = 0
	StoreType_STORE_TYPE_EXCHANGE StoreType = 1 // 兑换商店
)

// Enum value maps for StoreType.
var (
	StoreType_name = map[int32]string{
		0: "STORE_TYPE_NONE",
		1: "STORE_TYPE_EXCHANGE",
	}
	StoreType_value = map[string]int32{
		"STORE_TYPE_NONE":     0,
		"STORE_TYPE_EXCHANGE": 1,
	}
)

func (x StoreType) Enum() *StoreType {
	p := new(StoreType)
	*p = x
	return p
}

func (x StoreType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StoreType) Descriptor() protoreflect.EnumDescriptor {
	return file_store_type_proto_enumTypes[0].Descriptor()
}

func (StoreType) Type() protoreflect.EnumType {
	return &file_store_type_proto_enumTypes[0]
}

func (x StoreType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StoreType.Descriptor instead.
func (StoreType) EnumDescriptor() ([]byte, []int) {
	return file_store_type_proto_rawDescGZIP(), []int{0}
}

// StoreGoodsItem 商店商品静态及动态详情
type StoreGoodsItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GoodsId         uint32                 `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`                           // 商品流水ID (对应 StoreItem.xlsx 的 id)
	ItemId          uint32                 `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`                              // 售卖的道具ID (对应 Item.xlsx)
	CurrencyId      uint32                 `protobuf:"varint,3,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`                  // 消耗的货币道具ID (如 9001 装饰能量)
	Price           uint32                 `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`                                              // 售卖单价
	LimitMax        uint32                 `protobuf:"varint,5,opt,name=limit_max,json=limitMax,proto3" json:"limit_max,omitempty"`                        // 配置的最大限购数量 (0代表不限购)
	LimitLeft       uint32                 `protobuf:"varint,6,opt,name=limit_left,json=limitLeft,proto3" json:"limit_left,omitempty"`                     // 当前玩家剩余可购买数量
	RefreshType     uint32                 `protobuf:"varint,7,opt,name=refresh_type,json=refreshType,proto3" json:"refresh_type,omitempty"`               // 刷新类型 (对应枚举 RefreshType)
	NextRefreshSecs uint32                 `protobuf:"varint,8,opt,name=next_refresh_secs,json=nextRefreshSecs,proto3" json:"next_refresh_secs,omitempty"` // 距离下次刷新的剩余秒数
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StoreGoodsItem) Reset() {
	*x = StoreGoodsItem{}
	mi := &file_store_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreGoodsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreGoodsItem) ProtoMessage() {}

func (x *StoreGoodsItem) ProtoReflect() protoreflect.Message {
	mi := &file_store_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreGoodsItem.ProtoReflect.Descriptor instead.
func (*StoreGoodsItem) Descriptor() ([]byte, []int) {
	return file_store_type_proto_rawDescGZIP(), []int{0}
}

func (x *StoreGoodsItem) GetGoodsId() uint32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *StoreGoodsItem) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *StoreGoodsItem) GetCurrencyId() uint32 {
	if x != nil {
		return x.CurrencyId
	}
	return 0
}

func (x *StoreGoodsItem) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *StoreGoodsItem) GetLimitMax() uint32 {
	if x != nil {
		return x.LimitMax
	}
	return 0
}

func (x *StoreGoodsItem) GetLimitLeft() uint32 {
	if x != nil {
		return x.LimitLeft
	}
	return 0
}

func (x *StoreGoodsItem) GetRefreshType() uint32 {
	if x != nil {
		return x.RefreshType
	}
	return 0
}

func (x *StoreGoodsItem) GetNextRefreshSecs() uint32 {
	if x != nil {
		return x.NextRefreshSecs
	}
	return 0
}

var File_store_type_proto protoreflect.FileDescriptor

const file_store_type_proto_rawDesc = "" +
	"\n" +
	"\x10store_type.proto\x12\x04game\"\x86\x02\n" +
	"\x0eStoreGoodsItem\x12\x19\n" +
	"\bgoods_id\x18\x01 \x01(\rR\agoodsId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\rR\x06itemId\x12\x1f\n" +
	"\vcurrency_id\x18\x03 \x01(\rR\n" +
	"currencyId\x12\x14\n" +
	"\x05price\x18\x04 \x01(\rR\x05price\x12\x1b\n" +
	"\tlimit_max\x18\x05 \x01(\rR\blimitMax\x12\x1d\n" +
	"\n" +
	"limit_left\x18\x06 \x01(\rR\tlimitLeft\x12!\n" +
	"\frefresh_type\x18\a \x01(\rR\vrefreshType\x12*\n" +
	"\x11next_refresh_secs\x18\b \x01(\rR\x0fnextRefreshSecs*9\n" +
	"\tStoreType\x12\x13\n" +
	"\x0fSTORE_TYPE_NONE\x10\x00\x12\x17\n" +
	"\x13STORE_TYPE_EXCHANGE\x10\x01B1Z/github.com/lk2023060901/xiaojia-proto-game;gameb\x06proto3"

var (
	file_store_type_proto_rawDescOnce sync.Once
	file_store_type_proto_rawDescData []byte
)

func file_store_type_proto_rawDescGZIP() []byte {
	file_store_type_proto_rawDescOnce.Do(func() {
		file_store_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_store_type_proto_rawDesc), len(file_store_type_proto_rawDesc)))
	})
	return file_store_type_proto_rawDescData
}

var file_store_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_store_type_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_store_type_proto_goTypes = []any{
	(StoreType)(0),         // 0: game.StoreType
	(*StoreGoodsItem)(nil), // 1: game.StoreGoodsItem
}
var file_store_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_store_type_proto_init() }
func file_store_type_proto_init() {
	if File_store_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_store_type_proto_rawDesc), len(file_store_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_store_type_proto_goTypes,
		DependencyIndexes: file_store_type_proto_depIdxs,
		EnumInfos:         file_store_type_proto_enumTypes,
		MessageInfos:      file_store_type_proto_msgTypes,
	}.Build()
	File_store_type_proto = out.File
	file_store_type_proto_goTypes = nil
	file_store_type_proto_depIdxs = nil
}
